/*
 * generated by Xtext
 */
package de.cau.cs.kieler.sccharts.text3.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class Sct3UiModule extends de.cau.cs.kieler.sccharts.text3.ui.AbstractSct3UiModule {
	public Sct3UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
