/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.balloontrees.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class BalloonTreesUiModule extends AbstractBalloonTreesUiModule {

	public BalloonTreesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
