<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="s"
    nsURI="http://www.cau.de/cs/kieler/s" nsPrefix="s">
  <eClassifiers xsi:type="ecore:EClass" name="Program">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signals" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Signal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.s/src-gen/de/cau/cs/kieler/s/S.ecore#//State"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signals" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Signal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instructions" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.s/src-gen/de/cau/cs/kieler/s/S.ecore#//Instruction"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="continuation" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.s/src-gen/de/cau/cs/kieler/s/S.ecore#//State"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pause" eSuperTypes="platform:/resource/de.cau.cs.kieler.s/src-gen/de/cau/cs/kieler/s/S.ecore#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Term" eSuperTypes="platform:/resource/de.cau.cs.kieler.s/src-gen/de/cau/cs/kieler/s/S.ecore#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Halt" eSuperTypes="platform:/resource/de.cau.cs.kieler.s/src-gen/de/cau/cs/kieler/s/S.ecore#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Join" eSuperTypes="platform:/resource/de.cau.cs.kieler.s/src-gen/de/cau/cs/kieler/s/S.ecore#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Abort" eSuperTypes="platform:/resource/de.cau.cs.kieler.s/src-gen/de/cau/cs/kieler/s/S.ecore#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="If" eSuperTypes="platform:/resource/de.cau.cs.kieler.s/src-gen/de/cau/cs/kieler/s/S.ecore#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instructions" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.s/src-gen/de/cau/cs/kieler/s/S.ecore#//Instruction"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Goto" eSuperTypes="platform:/resource/de.cau.cs.kieler.s/src-gen/de/cau/cs/kieler/s/S.ecore#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.s/src-gen/de/cau/cs/kieler/s/S.ecore#//State"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fork" eSuperTypes="platform:/resource/de.cau.cs.kieler.s/src-gen/de/cau/cs/kieler/s/S.ecore#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.s/src-gen/de/cau/cs/kieler/s/S.ecore#//State"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Forke" eSuperTypes="platform:/resource/de.cau.cs.kieler.s/src-gen/de/cau/cs/kieler/s/S.ecore#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.s/src-gen/de/cau/cs/kieler/s/S.ecore#//State"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Emit" eSuperTypes="platform:/resource/de.cau.cs.kieler.s/src-gen/de/cau/cs/kieler/s/S.ecore#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Signal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Await" eSuperTypes="platform:/resource/de.cau.cs.kieler.s/src-gen/de/cau/cs/kieler/s/S.ecore#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Signal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Prio" eSuperTypes="platform:/resource/de.cau.cs.kieler.s/src-gen/de/cau/cs/kieler/s/S.ecore#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
