/*
 * generated by Xtext
 */
package de.cau.cs.kieler.annotations;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AnnotationsRuntimeModule extends de.cau.cs.kieler.annotations.AbstractAnnotationsRuntimeModule {

    @Override
    public Class<? extends org.eclipse.xtext.conversion.IValueConverterService>
        bindIValueConverterService() {
        
        return de.cau.cs.kieler.annotations.formatting.AnnotationsValueConverter.class;
    }

}
