/*
 * generated by Xtext
 */
package de.cau.cs.kieler.yakindu.model.stext.scoping;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import org.eclipse.xtext.scoping.impl.FilteringScope;
import org.eclipse.xtext.scoping.impl.SimpleScope;
import org.yakindu.sct.model.sgraph.Declaration;
import org.yakindu.sct.model.sgraph.Scope;
import org.yakindu.sct.model.sgraph.State;
import org.yakindu.sct.model.sgraph.Statechart;
import org.yakindu.sct.model.stext.scoping.STextScopeProvider;
import org.yakindu.sct.model.stext.stext.InterfaceScope;
import org.yakindu.sct.model.stext.stext.InternalScope;

import com.google.common.base.Predicate;
import com.google.common.collect.Iterables;
import com.google.common.collect.Lists;

import de.cau.cs.kieler.yakindu.model.stext.utils.SyncUtils;
import de.itemis.xtext.utils.jface.viewers.ContextElementAdapter;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping on
 * how and when to use it
 * 
 */
public class SynctextScopeProvider extends STextScopeProvider {
	/**
	 * Allow only unnamed top level Scope. It returns a list of top level
	 * declarations (signals and variables of parent states)
	 * 
	 */
	@Override
	public IScope scope_ElementReferenceExpression_reference(
			final EObject context, EReference reference) {
		return new SimpleScope(getUnnamedTopLevelScope(context, reference)
				.getAllElements());
	}
//        public IScope scope_ElementReferenceExpression_reference(
//                final EObject context, EReference reference) {
//          return new SimpleScope(Iterables.concat(
//                  getUnnamedTopLevelScope(context, reference).getAllElements(),
//                  Scopes.scopeFor(typeSystemUtils.getEnumerationTypes(typeSystem)).getAllElements()));
//}	
	

	/**
	 * Returns a scope with all toplevel declarations of parent States
	 */
	@Override
	protected IScope getUnnamedTopLevelScope(final EObject context,
			EReference reference) {
		final ContextElementAdapter provider = (ContextElementAdapter) EcoreUtil
				.getExistingAdapter(context.eResource(),
						ContextElementAdapter.class);
	        Statechart statechart = getStatechart(context);
	        if (statechart == null) {
	                return IScope.NULLSCOPE;
	        }	        
		if (provider == null) {		
		    State state = (State) statechart.getRegions().get(0).getVertices().get(0);
		        EList<Scope> scopes = state.getScopes();
		        List<EObject> scopeCandidates = Lists.newArrayList();
		        for (Scope scope : scopes) {
                                scopeCandidates.addAll(scope.getDeclarations());
		        }
		        return Scopes.scopeFor(scopeCandidates);
		}
		
		List<EObject> scopeCandidates = Lists.newArrayList();
		ArrayList<Declaration> declarations = SyncUtils
				.getAncestorDeclarations(provider.getElement().eContainer());
		if (declarations.size() > 0) {
			scopeCandidates.addAll(declarations);
			return Scopes.scopeFor(scopeCandidates);
		} else {
			return IScope.NULLSCOPE;
		}
	}
/*        protected IScope getUnnamedTopLevelScope(final EObject context,
                EReference reference) {
        List<EObject> scopeCandidates = Lists.newArrayList();
        Statechart statechart = getStatechart(context);
        if (statechart == null)
                return IScope.NULLSCOPE;
        EList<Scope> scopes = statechart.getScopes();
        for (Scope scope : scopes) {
                if (scope instanceof InterfaceScope) {
                        String name = ((InterfaceScope) scope).getName();
                        if (name == null || name.trim().length() == 0) {
                                scopeCandidates.addAll(scope.getDeclarations());
                        }
                } else if (scope instanceof InternalScope) {
                        scopeCandidates.addAll(scope.getDeclarations());
                }
        }
        return Scopes.scopeFor(scopeCandidates);
}*/	
}
