/* $**************  KCG Version 6.0.0b (build i19) **************
** Command: s2c -config U:/SIMULATION/Programmcode/ScadeSource/simulationsa/Simulation\kcg_s2c_config.txt
** Generation date: 2009-02-24T01:42:11
*************************************************************$ */
#include "kcg_consts.h"
const struct_3 INIT_TRACKEXTDATA_simulation = { kcg_false, 0.0, kcg_false, kcg_false };
/* simulation::INIT_TRACKEXTDATA */
const array_3 INIT_SPEEDARRAY_simulation = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 };
/* simulation::INIT_SPEEDARRAY */
const array_3 INIT_POSITIONARRAY_simulation = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 };
/* simulation::INIT_POSITIONARRAY */
const array_8 INIT_TRACKEXTDATAARRAY_simulation = { { kcg_false, 0.0, kcg_false,
    kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false,
    kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false,
    kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false,
    kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false,
    kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false,
    kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false,
    kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false,
    kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false,
    kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false,
    kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false,
    kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false,
    kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false,
    kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false,
    kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false,
    kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false,
    kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false,
    kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false,
    kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false,
    kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false,
    kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false,
    kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false,
    kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false,
    kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false,
    kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false } };
/* simulation::INIT_TRACKEXTDATAARRAY */
const array_3 INIT_SPEED_ARRAY_simulation = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 };
/* simulation::INIT_SPEED_ARRAY */
const struct_4 INIT_COMMANDS2_simulation = { { P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation }, { M_PRIMARY_simulation, M_PRIMARY_simulation,
    M_PRIMARY_simulation, M_PRIMARY_simulation, M_PRIMARY_simulation, M_PRIMARY_simulation,
    M_PRIMARY_simulation, M_PRIMARY_simulation, M_PRIMARY_simulation, M_PRIMARY_simulation,
    M_PRIMARY_simulation, M_PRIMARY_simulation, M_PRIMARY_simulation, M_OFF_simulation,
    M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
    M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
    M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
    M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
    M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
    M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
    M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation }, { 40.0,
    40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
    0.0 }, { S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation },
  { S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation }, { AL_NONE_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_BACKWARD_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation } };
/* simulation::INIT_COMMANDS2 */
const struct_5 INIT_FEEDBACK_simulation = { { { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } } }, { (-1.0), (-1.0), (-1.0), (-1.0),
    (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0),
    (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0),
    (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0),
    (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0),
    (-1.0), (-1.0), (-1.0), (-1.0) }, { (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0),
    (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0),
    (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0),
    (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0),
    (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0),
    (-1.0), (-1.0) }, { E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
    E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
    E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
    E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
    E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
    E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
    E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
    E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
    E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
    E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation }, { E_OK_simulation,
    E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
    E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
    E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
    E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
    E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
    E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
    E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
    E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
    E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
    E_OK_simulation, E_OK_simulation }, { { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false } } };
/* simulation::INIT_FEEDBACK */
const struct_7 INIT_DATA_LOCAL_simulation = { kcg_false, 0.0, AL_NONE_simulation };
/* simulation::INIT_DATA_LOCAL */
const struct_2 INIT_CONTACT_PAIR_simulation = { { kcg_false, D_UNKNOWN_simulation },
  { kcg_false, D_UNKNOWN_simulation } };
/* simulation::INIT_CONTACT_PAIR */
const array_4 INIT_SIGNALS_RED_simulation = { S_RED_simulation, S_RED_simulation,
  S_RED_simulation, S_RED_simulation, S_RED_simulation, S_RED_simulation, S_RED_simulation,
  S_RED_simulation, S_RED_simulation, S_RED_simulation, S_RED_simulation, S_RED_simulation,
  S_RED_simulation, S_RED_simulation, S_RED_simulation, S_RED_simulation, S_RED_simulation,
  S_RED_simulation, S_RED_simulation, S_RED_simulation, S_RED_simulation, S_RED_simulation,
  S_RED_simulation, S_RED_simulation, S_RED_simulation, S_RED_simulation, S_RED_simulation,
  S_RED_simulation, S_RED_simulation, S_RED_simulation, S_RED_simulation, S_RED_simulation,
  S_RED_simulation, S_RED_simulation, S_RED_simulation, S_RED_simulation, S_RED_simulation,
  S_RED_simulation, S_RED_simulation, S_RED_simulation, S_RED_simulation, S_RED_simulation,
  S_RED_simulation, S_RED_simulation, S_RED_simulation, S_RED_simulation, S_RED_simulation,
  S_RED_simulation, S_RED_simulation };
/* simulation::INIT_SIGNALS_RED */
const struct_6 INIT_DATA_GLOBAL_simulation = { { { P_STRAIGHT_simulation, P_STRAIGHT_simulation,
      P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
      P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
      P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
      P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
      P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
      P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
      P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
      P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
      P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
      P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
      P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
      P_STRAIGHT_simulation, P_STRAIGHT_simulation }, { M_OFF_simulation, M_OFF_simulation,
      M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
      M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
      M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
      M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
      M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
      M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
      M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
      M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
      M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
      M_OFF_simulation }, { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }, { S_OFF_simulation, S_OFF_simulation,
      S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
      S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
      S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
      S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
      S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
      S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
      S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
      S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
      S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
      S_OFF_simulation, S_OFF_simulation }, { S_OFF_simulation, S_OFF_simulation,
      S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
      S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
      S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
      S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
      S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
      S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
      S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
      S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
      S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
      S_OFF_simulation, S_OFF_simulation }, { AL_NONE_simulation, AL_NONE_simulation,
      AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
      AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
      AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
      AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
      AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
      AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
      AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
      AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
      AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
      AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
      AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
      AL_NONE_simulation, AL_NONE_simulation } }, { { { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
        { kcg_false, D_UNKNOWN_simulation } } }, { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }, { 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
    { E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
      E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
      E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
      E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
      E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
      E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
      E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
      E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
      E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
      E_OK_simulation, E_OK_simulation, E_OK_simulation }, { E_OK_simulation, E_OK_simulation,
      E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
      E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
      E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
      E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
      E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
      E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
      E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
      E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
      E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
      E_OK_simulation }, { { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false,
        0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false }, {
        kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
      { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
      { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
      { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
      { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
      { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
      { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
      { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
      { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
      { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
      { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
      { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
      { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
      { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
      { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
      { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
      { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
      { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
      { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
      { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
      { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
      { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
      { kcg_false, 0.0, kcg_false, kcg_false } } } };
/* simulation::INIT_DATA_GLOBAL */
const array_4 INIT_SIGNALARRAY_simulation = { S_OFF_simulation, S_OFF_simulation,
  S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
  S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
  S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
  S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
  S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
  S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
  S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
  S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
  S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
  S_OFF_simulation, S_OFF_simulation };
/* simulation::INIT_SIGNALARRAY */
const array_1 INIT_POINTARRAY_simulation = { P_STRAIGHT_simulation, P_STRAIGHT_simulation,
  P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
  P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
  P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
  P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
  P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
  P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
  P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
  P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
  P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
  P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
  P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
  P_STRAIGHT_simulation, P_STRAIGHT_simulation };
/* simulation::INIT_POINTARRAY */
const array_2 INIT_MOTORMODEARRAY_simulation = { M_OFF_simulation, M_OFF_simulation,
  M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
  M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
  M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
  M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
  M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
  M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
  M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
  M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
  M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
  M_OFF_simulation };
/* simulation::INIT_MOTORMODEARRAY */
const array_7 INIT_ERRORARRAY_simulation = { E_OK_simulation, E_OK_simulation, E_OK_simulation,
  E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
  E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
  E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
  E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
  E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
  E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
  E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
  E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
  E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation };
/* simulation::INIT_ERRORARRAY */
const struct_2 INIT_CONTACTPAIR_simulation = { { kcg_false, D_UNKNOWN_simulation },
  { kcg_false, D_UNKNOWN_simulation } };
/* simulation::INIT_CONTACTPAIR */
const array_6 INIT_CONTACTARRAY_simulation = { { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
    { kcg_false, D_UNKNOWN_simulation } } };
/* simulation::INIT_CONTACTARRAY */
const struct_10 INIT_CONTROLLERFEEDBACKSENSOR_simulation = { { { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
      { kcg_false, D_UNKNOWN_simulation } } }, { { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
    { kcg_false, 0.0, kcg_false, kcg_false } } };
/* simulation::INIT_CONTROLLERFEEDBACKSENSOR */
const array_4 INIT_SIGNALS_YELLOW_simulation = { S_YELLOW_simulation, S_YELLOW_simulation,
  S_YELLOW_simulation, S_YELLOW_simulation, S_YELLOW_simulation, S_YELLOW_simulation,
  S_YELLOW_simulation, S_YELLOW_simulation, S_YELLOW_simulation, S_YELLOW_simulation,
  S_YELLOW_simulation, S_YELLOW_simulation, S_YELLOW_simulation, S_YELLOW_simulation,
  S_YELLOW_simulation, S_YELLOW_simulation, S_YELLOW_simulation, S_YELLOW_simulation,
  S_YELLOW_simulation, S_YELLOW_simulation, S_YELLOW_simulation, S_YELLOW_simulation,
  S_YELLOW_simulation, S_YELLOW_simulation, S_YELLOW_simulation, S_YELLOW_simulation,
  S_YELLOW_simulation, S_YELLOW_simulation, S_YELLOW_simulation, S_YELLOW_simulation,
  S_YELLOW_simulation, S_YELLOW_simulation, S_YELLOW_simulation, S_YELLOW_simulation,
  S_YELLOW_simulation, S_YELLOW_simulation, S_YELLOW_simulation, S_YELLOW_simulation,
  S_YELLOW_simulation, S_YELLOW_simulation, S_YELLOW_simulation, S_YELLOW_simulation,
  S_YELLOW_simulation, S_YELLOW_simulation, S_YELLOW_simulation, S_YELLOW_simulation,
  S_YELLOW_simulation, S_YELLOW_simulation, S_YELLOW_simulation };
/* simulation::INIT_SIGNALS_YELLOW */
const array_4 INIT_SIGNALS_GREEN_simulation = { S_GREEN_simulation, S_GREEN_simulation,
  S_GREEN_simulation, S_GREEN_simulation, S_GREEN_simulation, S_GREEN_simulation,
  S_GREEN_simulation, S_GREEN_simulation, S_GREEN_simulation, S_GREEN_simulation,
  S_GREEN_simulation, S_GREEN_simulation, S_GREEN_simulation, S_GREEN_simulation,
  S_GREEN_simulation, S_GREEN_simulation, S_GREEN_simulation, S_GREEN_simulation,
  S_GREEN_simulation, S_GREEN_simulation, S_GREEN_simulation, S_GREEN_simulation,
  S_GREEN_simulation, S_GREEN_simulation, S_GREEN_simulation, S_GREEN_simulation,
  S_GREEN_simulation, S_GREEN_simulation, S_GREEN_simulation, S_GREEN_simulation,
  S_GREEN_simulation, S_GREEN_simulation, S_GREEN_simulation, S_GREEN_simulation,
  S_GREEN_simulation, S_GREEN_simulation, S_GREEN_simulation, S_GREEN_simulation,
  S_GREEN_simulation, S_GREEN_simulation, S_GREEN_simulation, S_GREEN_simulation,
  S_GREEN_simulation, S_GREEN_simulation, S_GREEN_simulation, S_GREEN_simulation,
  S_GREEN_simulation, S_GREEN_simulation, S_GREEN_simulation };
/* simulation::INIT_SIGNALS_GREEN */
const array_4 INIT_SIGNALS_simulation = { S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
  S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
  S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
  S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
  S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
  S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
  S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
  S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
  S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
  S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
  S_OFF_simulation };
/* simulation::INIT_SIGNALS */
const array_2 INIT_MOTORMODE_ARRAY_simulation = { M_PRIMARY_simulation, M_PRIMARY_simulation,
  M_PRIMARY_simulation, M_PRIMARY_simulation, M_PRIMARY_simulation, M_PRIMARY_simulation,
  M_PRIMARY_simulation, M_PRIMARY_simulation, M_PRIMARY_simulation, M_PRIMARY_simulation,
  M_PRIMARY_simulation, M_PRIMARY_simulation, M_PRIMARY_simulation, M_PRIMARY_simulation,
  M_PRIMARY_simulation, M_PRIMARY_simulation, M_PRIMARY_simulation, M_PRIMARY_simulation,
  M_PRIMARY_simulation, M_PRIMARY_simulation, M_PRIMARY_simulation, M_PRIMARY_simulation,
  M_PRIMARY_simulation, M_PRIMARY_simulation, M_PRIMARY_simulation, M_PRIMARY_simulation,
  M_PRIMARY_simulation, M_PRIMARY_simulation, M_PRIMARY_simulation, M_PRIMARY_simulation,
  M_PRIMARY_simulation, M_PRIMARY_simulation, M_PRIMARY_simulation, M_PRIMARY_simulation,
  M_PRIMARY_simulation, M_PRIMARY_simulation, M_PRIMARY_simulation, M_PRIMARY_simulation,
  M_PRIMARY_simulation, M_PRIMARY_simulation, M_PRIMARY_simulation, M_PRIMARY_simulation,
  M_PRIMARY_simulation, M_PRIMARY_simulation, M_PRIMARY_simulation, M_PRIMARY_simulation,
  M_PRIMARY_simulation, M_PRIMARY_simulation };
/* simulation::INIT_MOTORMODE_ARRAY */
const array_1 INIT_POINTS_simulation = { P_STRAIGHT_simulation, P_STRAIGHT_simulation,
  P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
  P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
  P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
  P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
  P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
  P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
  P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
  P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
  P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
  P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
  P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
  P_STRAIGHT_simulation, P_STRAIGHT_simulation };
/* simulation::INIT_POINTS */
const array_7 TEST_ERROR2_simulation = { E_TRACK_OCCUPIED_simulation, E_OK_simulation,
  E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
  E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
  E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
  E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
  E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
  E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
  E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
  E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
  E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
  E_OK_simulation };
/* simulation::TEST_ERROR2 */
const array_7 TEST_ERROR_1_simulation = { E_OK_simulation, E_OK_simulation, E_OK_simulation,
  E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
  E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
  E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
  E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
  E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
  E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
  E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
  E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
  E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation };
/* simulation::TEST_ERROR_1 */
const array_5 INIT_TRAIN_ARRAY_simulation = { AL_NONE_simulation, AL_NONE_simulation,
  AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
  AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
  AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
  AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
  AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
  AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
  AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
  AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
  AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
  AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
  AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
  AL_NONE_simulation, AL_NONE_simulation };
/* simulation::INIT_TRAIN_ARRAY */
const struct_4 MAX_COMMANDS_simulation = { { P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation }, { M_PRIMARY_simulation, M_PRIMARY_simulation,
    M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
    M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
    M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
    M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
    M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
    M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
    M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
    M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
    M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
    M_OFF_simulation }, { 10.0, 10.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0, 0.0 }, { S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation }, { S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation },
  { AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation } };
/* simulation::MAX_COMMANDS */
const struct_7 ENTER_TRAIN_simulation = { kcg_true, 0.0, AL_NONE_simulation };
/* simulation::ENTER_TRAIN */
const struct_8 INIT_DATA_ALL_simulation = { { { { P_STRAIGHT_simulation, P_STRAIGHT_simulation,
        P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
        P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
        P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
        P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
        P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
        P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
        P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
        P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
        P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
        P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
        P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
        P_STRAIGHT_simulation, P_STRAIGHT_simulation }, { M_OFF_simulation, M_OFF_simulation,
        M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
        M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
        M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
        M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
        M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
        M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
        M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
        M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
        M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
        M_OFF_simulation }, { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }, { S_OFF_simulation, S_OFF_simulation,
        S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
        S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
        S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
        S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
        S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
        S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
        S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
        S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
        S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
        S_OFF_simulation, S_OFF_simulation }, { S_OFF_simulation, S_OFF_simulation,
        S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
        S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
        S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
        S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
        S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
        S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
        S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
        S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
        S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
        S_OFF_simulation, S_OFF_simulation }, { AL_NONE_simulation, AL_NONE_simulation,
        AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
        AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
        AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
        AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
        AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
        AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
        AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
        AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
        AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
        AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
        AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
        AL_NONE_simulation, AL_NONE_simulation } }, { { { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } }, { { kcg_false, D_UNKNOWN_simulation },
          { kcg_false, D_UNKNOWN_simulation } } }, { (-1.0), (-1.0), (-1.0), (-1.0),
        (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0),
        (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0),
        (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0),
        (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0),
        (-1.0), (-1.0), (-1.0), (-1.0) }, { (-1.0), (-1.0), (-1.0), (-1.0), (-1.0),
        (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0),
        (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0),
        (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0),
        (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), (-1.0),
        (-1.0), (-1.0), (-1.0) }, { E_OK_simulation, E_OK_simulation, E_OK_simulation,
        E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
        E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
        E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
        E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
        E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
        E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
        E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
        E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
        E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation },
      { E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
        E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
        E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
        E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
        E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
        E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
        E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
        E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
        E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation, E_OK_simulation,
        E_OK_simulation, E_OK_simulation, E_OK_simulation }, { { kcg_false, 0.0,
          kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false,
          0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
        { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
        { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
        { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
        { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
        { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
        { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
        { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
        { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
        { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
        { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
        { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
        { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
        { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
        { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
        { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
        { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
        { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
        { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
        { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
        { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
        { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false },
        { kcg_false, 0.0, kcg_false, kcg_false }, { kcg_false, 0.0, kcg_false, kcg_false } } } },
  { kcg_false, 0.0, AL_NONE_simulation } };
/* simulation::INIT_DATA_ALL */
const struct_4 INIT_COMMANDS_simulation = { { P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation, P_STRAIGHT_simulation,
    P_STRAIGHT_simulation, P_STRAIGHT_simulation }, { M_OFF_simulation, M_OFF_simulation,
    M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
    M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
    M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
    M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
    M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
    M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
    M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
    M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
    M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation, M_OFF_simulation,
    M_OFF_simulation }, { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0, 0.0 }, { S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation }, { S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation,
    S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation, S_OFF_simulation },
  { AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation,
    AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation, AL_NONE_simulation } };
/* simulation::INIT_COMMANDS */

/* $**************  KCG Version 6.0.0b (build i19) **************
** kcg_consts.c
** Generation date: 2009-02-24T01:42:11
*************************************************************$ */
