<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="scgdep" nsURI="http://kieler.cs.cau.de/scgdep/0.1.0" nsPrefix="scgdep">
  <eClassifiers xsi:type="ecore:EClass" name="Dependency" eSuperTypes="../../de.cau.cs.kieler.scg/model/scg.ecore#//Link"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbsoluteWrite_Read" eSuperTypes="#//Dependency"/>
  <eClassifiers xsi:type="ecore:EClass" name="RelativeWrite_Read" eSuperTypes="#//Dependency"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbsoluteWrite_RelativeWrite" eSuperTypes="#//Dependency"/>
  <eClassifiers xsi:type="ecore:EClass" name="Write_Write" eSuperTypes="#//Dependency"/>
</ecore:EPackage>
