rm plugins/de.cau.cs.kieler.kico/src/de/cau/cs/kieler/kico/KielerCompiler.java
rm plugins/de.cau.cs.kieler.kico.klighd/.classpath
rm plugins/de.cau.cs.kieler.kico.klighd/.project
rm plugins/de.cau.cs.kieler.kico.klighd/.settings/org.eclipse.jdt.core.prefs
rm plugins/de.cau.cs.kieler.kico.klighd/META-INF/MANIFEST.MF
rm plugins/de.cau.cs.kieler.kico.klighd/build.properties
rm plugins/de.cau.cs.kieler.kico.klighd/epl-v10.html
rm plugins/de.cau.cs.kieler.kico.klighd/icons/KiCoKlighViewIcon.png
rm plugins/de.cau.cs.kieler.kico.klighd/icons/KiCoKlighViewIcon2.png
rm plugins/de.cau.cs.kieler.kico.klighd/plugin.xml
rm plugins/de.cau.cs.kieler.kico.klighd/pom.xml
rm plugins/de.cau.cs.kieler.kico.klighd/src/de/cau/cs/kieler/kico/klighd/KiCoDiagramSynthesis.xtend
rm plugins/de.cau.cs.kieler.kico.klighd/src/de/cau/cs/kieler/kico/klighd/KiCoKlighdPlugin.java
rm plugins/de.cau.cs.kieler.kico.klighd/src/de/cau/cs/kieler/kico/klighd/KiCoSelectionAction.java
rm plugins/de.cau.cs.kieler.kico.klighd/src/de/cau/cs/kieler/kico/klighd/KiCoSelectionView.java
rm plugins/de.cau.cs.kieler.kico.klighd/src/de/cau/cs/kieler/kico/klight/layout/TransformationDummyLayoutConfig.java
rm plugins/de.cau.cs.kieler.sccharts/plugin.xml