/*
 * generated by Xtext
 */
package de.cau.cs.kieler.core.annotations.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AnnotationsUiModule extends de.cau.cs.kieler.core.annotations.ui.AbstractAnnotationsUiModule {
	public AnnotationsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
