/*
 * generated by Xtext
 */
package de.cau.cs.kieler.kicool


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class KiCoolStandaloneSetup extends KiCoolStandaloneSetupGenerated {

	def static doSetup() {
		return new KiCoolStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
