<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mymodel"
    nsURI="http://mymodel/1.0" nsPrefix="mymodel">
  <eClassifiers xsi:type="ecore:EClass" name="MyString" eSuperTypes="#//MyData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MyInt" eSuperTypes="#//MyData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MyData" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="MyConst" eSuperTypes="#//MyData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//myConstValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="myConstValue">
    <eLiterals name="PI"/>
    <eLiterals name="E" value="1"/>
    <eLiterals name="NULL" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MyList" eSuperTypes="#//MyData">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//MyData" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MyDataModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//MyData" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
