<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="retypingSynccharts"
    nsURI="http://www.cau.de/cs/kieler/synccharts/dsl/RetypingSynccharts" nsPrefix="retypingSynccharts">
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isInitial" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isFinal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stateKind" eType="#//StateType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stateName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateContent" eType="#//StateContent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingTransitions" upperBound="-1"
        eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="declaredStateType" eType="#//StateType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="declaredStateName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateContent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exitActions" upperBound="-1"
        eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entryActions" upperBound="-1"
        eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="innerAction" upperBound="-1"
        eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signalsAndVariables" upperBound="-1"
        eType="#//ValuedObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="innerStates" upperBound="-1"
        eType="#//State" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parallelStates" upperBound="-1"
        eType="#//State" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StateType">
    <eLiterals name="PSEUDO" literal="PSEUDO"/>
    <eLiterals name="REFERENCE" value="1" literal="reference"/>
    <eLiterals name="TEXTUAL" value="2" literal="textual"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="effects" upperBound="-1"
        eType="#//Effect" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceStateName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transitionType" eType="#//TransitionType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetStateName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaredTargetState" eType="#//State"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitionLabel" eType="#//Action"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TransitionType">
    <eLiterals name="STRONGABORT" literal="o->"/>
    <eLiterals name="WEAKABORT" value="1" literal="-->"/>
    <eLiterals name="NORMALTERMINATION" value="2" literal=">->"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Effect"/>
  <eClassifiers xsi:type="ecore:EClass" name="Emission" eSuperTypes="#//Effect">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" eType="#//Signal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newValue" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assignment" eSuperTypes="#//Effect">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SignalReference" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="#//Signal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableReference" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValuedObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Signal" eSuperTypes="#//ValuedObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//ValuedObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntValue" eSuperTypes="#//Value #//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FloatValue" eSuperTypes="#//Value #//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanValue" eSuperTypes="#//Value #//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value"/>
  <eClassifiers xsi:type="ecore:EClass" name="HostCode" eSuperTypes="#//Effect">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operatorKind" eType="#//OperatorKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//OperatorKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subExpressions" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operations" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operators" eType="#//OperatorKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OperatorKind">
    <eLiterals name="EQ" literal="="/>
    <eLiterals name="LT" value="1" literal="&lt;"/>
    <eLiterals name="LEQ" value="2" literal="&lt;="/>
    <eLiterals name="GT" value="3" literal=">"/>
    <eLiterals name="GEQ" value="4" literal=">="/>
    <eLiterals name="NOT" value="5" literal="not"/>
    <eLiterals name="AND" value="6" literal="and"/>
    <eLiterals name="OR" value="7" literal="or"/>
    <eLiterals name="ADD" value="8" literal="+"/>
    <eLiterals name="SUB" value="9" literal="-"/>
    <eLiterals name="MULT" value="10" literal="*"/>
    <eLiterals name="DIV" value="11" literal="div"/>
    <eLiterals name="MOD" value="12" literal="mod"/>
    <eLiterals name="VAL" value="13" literal="?"/>
    <eLiterals name="PRE" value="14" literal="pre"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subExpression" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
