<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="circuit" nsURI="http://kieler.cs.cau.de/circuit" nsPrefix="circuit">
  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="#//Linkable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="innerActors" upperBound="-1"
        eType="#//Actor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="innerLinks" upperBound="-1"
        eType="#//Link" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" upperBound="-1"
        eType="#//Port" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port" eSuperTypes="#//Linkable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="../../de.cau.cs.kieler.core.annotations/model/annotations.ecore#//NamedObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Linkable"
        eOpposite="#//Linkable/outgoingLinks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Linkable"
        eOpposite="#//Linkable/incomingLinks"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Linkable" abstract="true" eSuperTypes="../../de.cau.cs.kieler.core.annotations/model/annotations.ecore#//NamedObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingLinks" upperBound="-1"
        eType="#//Link" eOpposite="#//Link/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingLinks" upperBound="-1"
        eType="#//Link" eOpposite="#//Link/source"/>
  </eClassifiers>
</ecore:EPackage>
