<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="esterel"
    nsURI="http://www.cau.de/cs/kieler/esterel/Esterel" nsPrefix="esterel">
  <eClassifiers xsi:type="ecore:EClass" name="Program">
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" upperBound="-1"
        eType="#//Module" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modInt" eType="#//ModuleInterface"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modBody" eType="#//ModuleBody"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" upperBound="-1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleInterface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="intSignalDecl" upperBound="-1"
        eType="#//SignalDecl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intTypeDecl" upperBound="-1"
        eType="#//TypeDecl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intSensorDecl" upperBound="-1"
        eType="#//SensorDecl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intConstantDecl" upperBound="-1"
        eType="#//ConstantDecl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intRelationDecl" upperBound="-1"
        eType="#//RelationDecl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intFunctionDecl" upperBound="-1"
        eType="#//FunctionDecl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intProcedureDecl" upperBound="-1"
        eType="#//ProcedureDecl" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SignalDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" upperBound="-1"
        eType="#//Signal" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SensorDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensor" upperBound="-1"
        eType="#//Sensor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationDecl"/>
  <eClassifiers xsi:type="ecore:EClass" name="RelationType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationImplication" eSuperTypes="#//RelationType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="first" eType="#//Signal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="second" eType="#//Signal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationIncompatibility" eSuperTypes="#//RelationType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomp" unique="false"
        upperBound="-1" eType="#//Signal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" upperBound="-1" eType="#//Type"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstantDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constant" upperBound="-1"
        eType="#//OneTypeConstantDecl" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OneTypeConstantDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constant" upperBound="-1"
        eType="#//Constant" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" upperBound="-1"
        eType="#//Function" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idList" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcedureDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="procedure" upperBound="-1"
        eType="#//Procedure" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Procedure">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idList" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assignment" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//DataExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Abort" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="#//Statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//AbortBody"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbortBody">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbortInstance" eSuperTypes="#//AbortBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="delay" eType="#//DelayExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbortCase" eSuperTypes="#//AbortBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cases" upperBound="-1"
        eType="#//AbortCaseSingle" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbortCaseSingle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="delay" eType="#//DelayExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Await" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//AwaitBody"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AwaitBody"/>
  <eClassifiers xsi:type="ecore:EClass" name="AwaitInstance" eSuperTypes="#//AwaitBody"/>
  <eClassifiers xsi:type="ecore:EClass" name="AwaitCase" eSuperTypes="#//AwaitBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cases" upperBound="-1"
        eType="#//AbortCaseSingle" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Do" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="#//Statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoUpto">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//DelayExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoWatching">
    <eStructuralFeatures xsi:type="ecore:EReference" name="delay" eType="#//DelayExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//DoWatchingEnd"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoWatchingEnd">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Emit" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" eType="#//Signal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tick" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//DataExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EveryDo" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="delay" eType="#//DelayExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Exit" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trap" eType="#//TrapDecl"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataExpr" eType="#//DataExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Halt" eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="IfTest" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//DataExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="then" eType="#//ThenPart"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseIf" eType="#//ElsIfPart"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="#//ElsePart"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElsIfPart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elsif" upperBound="-1"
        eType="#//ElsIf" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElsIf">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//DataExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="then" eType="#//ThenPart"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ThenPart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElsePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Loop" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//LoopBody"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//LoopEach"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoopEach"/>
  <eClassifiers xsi:type="ecore:EClass" name="LoopDelay" eSuperTypes="#//LoopEach">
    <eStructuralFeatures xsi:type="ecore:EReference" name="delay" eType="#//DelayExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoopBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Nothing" eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Pause" eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Present" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//PresentBody"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elsePart" eType="#//ElsePart"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PresentBody"/>
  <eClassifiers xsi:type="ecore:EClass" name="PresentEventBody" eSuperTypes="#//PresentBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="#//PresentEvent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenPart" eType="#//ThenPart"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PresentCaseList" eSuperTypes="#//PresentBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="case" upperBound="-1" eType="#//PresentCase"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PresentCase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="#//PresentEvent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PresentEvent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//SigExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Repeat" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="positive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataExpr" eType="#//DataExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Run" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" eType="#//ModuleRenaming"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="list" eType="#//RenamingList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleRenaming">
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" eType="#//Module"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="renamed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RenamingList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="list" upperBound="-1" eType="#//Renaming"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Renaming">
    <eStructuralFeatures xsi:type="ecore:EReference" name="renaming" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeRenaming">
    <eStructuralFeatures xsi:type="ecore:EReference" name="newName" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldName" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstantRenaming">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionRenaming">
    <eStructuralFeatures xsi:type="ecore:EReference" name="newName" eType="#//Function"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldName" eType="#//Function"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcedureRenaming">
    <eStructuralFeatures xsi:type="ecore:EReference" name="newName" eType="#//Procedure"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldName" eType="#//Procedure"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SignalRenaming">
    <eStructuralFeatures xsi:type="ecore:EReference" name="newName" eType="#//Signal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldName" eType="#//Signal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalSignalDecl" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signalList" eType="#//LocalSignalList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalSignalList"/>
  <eClassifiers xsi:type="ecore:EClass" name="Suspend" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="#//Statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="delay" eType="#//DelayExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sustain" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" eType="#//Signal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tick" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataExpr" eType="#//DataExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trap" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trapDeclList" eType="#//TrapDeclList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="#//Statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trapHandlerList" eType="#//TrapHandlerList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrapDeclList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trapDecl" upperBound="-1"
        eType="#//TrapDecl" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrapDecl">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="channelDesc" eType="#//ChannelDescription"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrapHandlerList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trapHandler" upperBound="-1"
        eType="#//TrapHandler" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrapHandler">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trapExpr" eType="#//TrapExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="varDecl" eType="#//VariableDecl"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="varList" eType="#//VariableList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//VariableDecl"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableList">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//DataExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//VariableList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WeakAbort" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="#//Statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="weakAbortBody" eType="#//WeakAbortBody"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WeakAbortBody">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WeakAbortInstance" eSuperTypes="#//WeakAbortBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="delay" eType="#//DelayExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WeakAbortCase" eSuperTypes="#//WeakAbortBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cases" upperBound="-1"
        eType="#//AbortCaseSingle" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataExpr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//DataUnaryExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//DataExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//DataExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataUnaryExpr" eSuperTypes="#//DataExpr"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataValueID" eSuperTypes="#//DataUnaryExpr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataValueFloat" eSuperTypes="#//DataUnaryExpr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataValueBoolean" eSuperTypes="#//DataUnaryExpr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataValueInt" eSuperTypes="#//DataUnaryExpr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataValueString" eSuperTypes="#//DataUnaryExpr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataBlock" eSuperTypes="#//DataUnaryExpr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataExpr" eType="#//DataExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataCurrent" eSuperTypes="#//DataUnaryExpr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" eType="#//Signal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tick" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataPre" eSuperTypes="#//DataUnaryExpr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" eType="#//Signal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tick" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataTrap" eSuperTypes="#//DataUnaryExpr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trap" eType="#//TrapDecl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataFunction" eSuperTypes="#//DataUnaryExpr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" eType="#//Function"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataExpr" upperBound="-1"
        eType="#//DataExpr" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrapExpr"/>
  <eClassifiers xsi:type="ecore:EClass" name="SigExpr" eSuperTypes="#//TrapExpr #//DelayEvent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="andExpr" upperBound="-1"
        eType="#//SigExprAND" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SigExprAND">
    <eStructuralFeatures xsi:type="ecore:EReference" name="unaExpr" upperBound="-1"
        eType="#//SigExprUnary" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SigExprUnary">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sigExpr" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DelayExpr" eSuperTypes="#//AwaitInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="#//Statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="#//DelayEvent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//DataExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DelayEvent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" eType="#//Signal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tick" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChannelDescription">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataExpr" eType="#//DataExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Signal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="channel" eType="#//ChannelDescription"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Input" eSuperTypes="#//SignalDecl"/>
  <eClassifiers xsi:type="ecore:EClass" name="Output" eSuperTypes="#//SignalDecl"/>
  <eClassifiers xsi:type="ecore:EClass" name="InputOutput" eSuperTypes="#//SignalDecl"/>
  <eClassifiers xsi:type="ecore:EClass" name="Return" eSuperTypes="#//SignalDecl"/>
  <eClassifiers xsi:type="ecore:EClass" name="Relation" eSuperTypes="#//RelationDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="relation" upperBound="-1"
        eType="#//RelationType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parallel" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sequence" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalSignal" eSuperTypes="#//LocalSignalList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" upperBound="-1"
        eType="#//Signal" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
