mod TESTDATA is
including STEPSEM .
including TRANS-ACTION-CONFLICTS .

ops u v w x y z v1 v2 : -> Variable [ctor] .

ops ac1 ac2 ac3 ac4 ac5 ac6 ac7 ac8 ac9 ac0 ac01 : -> Action .
eq ac0 = Ac(readSet x write y) .
eq ac01 = Ac(readSet x write y) .
eq ac1 = Ac(readSet u write u) .
eq ac2 = Ac(readSet x, y write w) .
eq ac3 = Ac(readSet x, z write y) .
eq ac4 = Ac(readSet x, u write y) .
eq ac5 = Ac(readSet x, u, w write y) .
eq ac6 = Ac(readSet x, v write y) .
eq ac7 = Ac(readSet z write y) .
eq ac8 = Ac(readSet u write y) .
eq ac9 = Ac(readSet empty write empty) .


ops srtaTrans bcTrans jkTrans : -> Transitions .
eq bcTrans = (((rR "0") : (C "A") : (R "1") : (C "B"))  
	e1 Gd ac1 ac1 ac1
	((rR "0") : (C "A") : (R "1") : (C "C"))
	((rR "0") : (C "A") : (R "1")) 
	) .
	
eq jkTrans = (((rR "0") : (C "A") : (R "4") : (C "J"))  
	e1 Gd ac1 ac1 ac1 
	((rR "0") : (C "A") : (R "4") : (C "K"))
	((rR "0") : (C "A") : (R "4")) 
	) .
	
eq srtaTrans = (bcTrans, jkTrans) . 

ops srtaVerts bSt cSt jSt kSt : -> Verts .

eq bSt = ((rR "0") : (C "A") : (R "1") : (C "B")) .
eq cSt = ((rR "0") : (C "A") : (R "1") : (C "C")) .
eq jSt = ((rR "0") : (C "A") : (R "4") : (C "J")) .
eq kSt = ((rR "0") : (C "A") : (R "4") : (C "K")) .


eq srtaVerts = (rR "0").Region , 
	((rR "0") : (C "A")),
	((rR "0") : (C "A") : (R "1")),
	bSt,
	((rR "0") : (C "A") : (R "1") : (C "D")),
	cSt,
	jSt,
	kSt,
	((rR "0") : (C "A") : (R "4") : (C "L")),
	((rR "0") : (C "A") : (R "4") : (C "M")) .



ops srtaDefs srtaD : -> Defaults .
eq srtaDefs = 
	((rR "0") default ((rR "0") : (C "A"))) ,
	(((rR "0") : (C "A") : (R "1")) default ((rR "0") : (C "A") : (R "1") : (C "B"))) , 
	 (((rR "0") : (C "A") : (R "4")) default ((rR "0") : (C "A") : (R "4") : (C "J"))) .

eq srtaD = ((rR "0") default ((rR "0") : (C "A"))) .

op srtaSm : -> StateMachine .
eq srtaSm = (SM srtaVerts srtaDefs empty empty srtaTrans) .
	
ops srtaConf : -> Verts .
eq srtaConf = rR "0" , 
	 ((rR "0") : (C "A")) ,    
	 ((rR "0") : (C "A") : (R "1")) ,    
	 ((rR "0") : (C "A") : (R "1") : (C "B")) ,    
	 ((rR "0") : (C "A") : (R "4") : (C "J")) .
	 
op srtaHconf : -> HistoryConfs .
eq srtaHconf = empty .

op srtaLtss : ->  LtsState .
eq srtaLtss = (LTSS srtaSm srtaConf srtaHconf anyevent : "e0") .







ops testTrans1 testTrans2 testTrans3 testTrans4 : -> ModTransition .
eq testTrans1 = (((R "a") : (C "0") : (R "a") : (C "2"))
     anyevent : "e1" Gd Ac(readSet x write y) Ac(readSet x write y) Ac(readSet x write y)
 ((R "a") : (C "0") : (R "a") : (C "3") : (R "a") : (C "9"))
 ((R "a") : (C "0") : (R "a"))) .
eq testTrans2 = (((R "a") : (C "0") : (R "a") : (C "2"))
     anyevent : "e2" Gd Ac(readSet v,z write y, x) Ac(readSet v,z write y, x) Ac(readSet v,z write y, x)
 ((R "a") : (C "0") : (R "a") : (C "3") : (R "a") : (C "9"))
 ((R "a") : (C "0") : (R "a"))) .
eq testTrans3 = (((R "a") : (C "0") : (R "a") : (C "2"))
     anyevent : "e3" Gd Ac(readSet u,y write v) Ac(readSet u,y write v) Ac(readSet u,y write v)
 ((R "a") : (C "0") : (R "a") : (C "3") : (R "a") : (C "9"))
 ((R "a") : (C "0") : (R "a"))) .
eq testTrans4 = (((R "a") : (C "0") : (R "a") : (C "2"))
     anyevent : "e4" Gd Ac(readSet v1 write v2) Ac(readSet v1 write v2) Ac(readSet v1 write v2)
 ((R "a") : (C "0") : (R "a") : (C "3") : (R "a") : (C "9"))
 ((R "a") : (C "0") : (R "a"))) .


op mstates : -> Verts .
eq mstates = R "a" ,    
	((R "a") : (C "0")),
	((R "a") : (C "0") : (R "a")) , 
	((R "a") : (C "0") : (R "a") : (C "1")) ,    
	((R "a") : (C "0") : (R "a") : (C "1") : R "a") ,    
	((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "5") , 
	((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "6") ,    
	((R "a") : (C "0") : (R "a") : (C "1") : R "a" : F "f") , 
	((R "a") : (C "0") : (R "a") : (C "1") : R "a" : H) , 
	((R "a") : (C "0") : (R "a") : (C "1") : R "a" : H*) , 
	((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "6" : R "a") , 
	((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "6" : R "a" : C "7") , 
	((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "6" : R "a" : C "8") , 
	((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "6" : R "a" : H*) , 
	((R "a") : (C "0") : (R "a") : (C "2")) , 
	((R "a") : (C "0") : (R "a") : (C "3")) , 
	((R "a") : (C "0") : (R "a") : (C "3") : (R "a")) , 
	((R "a") : (C "0") : (R "a") : (C "3") : (R "a") : (C "9")) , 
	((R "a") : (C "0") : (R "a") : (C "3") : (R "a") : (C "10")) , 
	((R "a") : (C "0") : (R "a") : (C "3") : (R "b")) , 
	((R "a") : (C "0") : (R "a") : (C "3") : (R "b") : (C "11")) , 	
	((R "a") : (C "0") : (R "a") : (C "3") : (R "b") : (C "12")) , 	
	((R "a") : (C "0") : (R "a") : (C "4")) .
	
op mtrans : -> Transitions .
eq mtrans = (
	*** t2
    (((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "5")  
	anyevent : "e5Final" Gd ac0 ac0 ac0 
	((R "a") : (C "0") : (R "a") : (C "1") : R "a" : F "f")
	((R "a") : (C "0") : (R "a") : (C "1") : R "a")) , 
	*** t26
    (((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "5")  
	anyevent : "e1" Gd ac0 ac0 ac0 
	((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "6")
	((R "a") : (C "0") : (R "a") : (C "1") : R "a")) , 
	*** t1
    (((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "6")  
	anyevent : "e6Final" Gd ac0 ac0 ac0 
	((R "a") : (C "0") : (R "a") : (C "1") : R "a" : F "f")
	((R "a") : (C "0") : (R "a") : (C "1") : R "a")) , 
	*** t15
    (((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "6" : R "a" : C "7")  
	anyevent : "e1" Gd ac0 ac0 ac0 
	((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "6" : R "a" : C "8")
	((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "6" : R "a")) , 
	*** t3
    (((R "a") : (C "0") : (R "a") : (C "2"))
    	anyevent : "e1" Gd ac0 ac0 ac0 
	((R "a") : (C "0") : (R "a") : (C "1"))
	((R "a") : (C "0") : (R "a"))) ,      
	*** t24
    (((R "a") : (C "0") : (R "a") : (C "1"))
   	anyevent : "e1" Gd ac0 ac0 ac0 
	((R "a") : (C "0") : (R "a") : (C "2"))
	((R "a") : (C "0") : (R "a"))) , 
	*** t22   
    ((((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "6" : R "a" : C "8"))
    	anyevent : "e1" Gd ac0 ac0 ac0 
	((R "a") : (C "0") : (R "a") : (C "2"))
	((R "a") : (C "0") : (R "a"))) ,      
	*** t16
    (((R "a") : (C "0") : (R "a") : (C "2"))
    	anyevent : "e1" Gd ac0 ac0 ac0 
	((R "a") : (C "0") : (R "a") : (C "3") : (R "a") : (C "9"))
	((R "a") : (C "0") : (R "a"))) , 
	*** t9
    (((R "a") : (C "0") : (R "a") : (C "2"))
    	anyevent : "e2" Gd ac0 ac0 ac0 
	(((R "a") : (C "0") : (R "a") : (C "3") : (R "a") : (C "9")) ,    
		((R "a") : (C "0") : (R "a") : (C "3") : (R "b") : (C "11")))
	((R "a") : (C "0") : (R "a"))) , 
	*** t8
    ((((R "a") : (C "0") : (R "a") : (C "3") : (R "a") : (C "10")) ,    
		((R "a") : (C "0") : (R "a") : (C "3") : (R "b") : (C "12")))
    	anyevent : "e1" Gd ac0 ac0 ac0 
	((R "a") : (C "0") : (R "a") : (C "4"))	
	((R "a") : (C "0") : (R "a"))) , 
	*** t19
    (((R "a") : (C "0") : (R "a") : (C "3") : (R "a") : (C "9"))
	anyevent : "e1" Gd ac0 ac0 ac0  
	((R "a") : (C "0") : (R "a") : (C "3") : (R "a") : (C "10"))
	((R "a") : (C "0") : (R "a") : (C "3") : (R "a"))) , 
	*** t20
    (((R "a") : (C "0") : (R "a") : (C "3") : (R "b") : (C "11"))
	anyevent : "e1" Gd ac0 ac0 ac0
	((R "a") : (C "0") : (R "a") : (C "3") : (R "b") : (C "12"))
        ((R "a") : (C "0") : (R "a") : (C "3") : (R "b"))) , 
	***t17
    (((R "a") : (C "0") : (R "a") : (C "2"))
    	anyevent : "esh" Gd ac0 ac0 ac0  
	((R "a") : (C "0") : (R "a") : (C "1") : R "a" : H)
	((R "a") : (C "0") : (R "a"))) , 
	***t18
    (((R "a") : (C "0") : (R "a") : (C "2"))
    	anyevent : "edh" Gd ac0 ac0 ac0  
	((R "a") : (C "0") : (R "a") : (C "1") : R "a" : H* )
	((R "a") : (C "0") : (R "a"))) 
	***t25
    ) .

op mdefs : -> Defaults .
eq mdefs = (((R "a") : (C "0") : (R "a") : (C "1") : R "a") default 
		((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "5")) , 
	(((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "6" : R "a") 
		default 
		((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "6" : R "a" : C "7")) , 
	 (((R "a") : (C "0") : (R "a")) default 
	 ((R "a") : (C "0") : (R "a") : (C "2"))) , 
	 (((R "a") : (C "0") : (R "a") : (C "3") : (R "b")) default
	 ((R "a") : (C "0") : (R "a") : (C "3") : (R "b") : (C "12"))) .

op msdefs : -> ShallowDefaults .
eq msdefs = ((R "a") : (C "0") : (R "a") : (C "1") : R "a") shallowdefault ((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "5") .


op mddefs : -> DeepDefaults .
eq mddefs = ((R "a") : (C "0") : (R "a") : (C "1") : R "a") deepdefault ((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "6") .

op sm : -> StateMachine .
eq sm = (SM mstates mdefs msdefs mddefs mtrans) .

ops mconf mconf2 : -> Verts .
eq mconf = R "a" , 
	 ((R "a") : (C "0")) ,    
	 ((R "a") : (C "0") : (R "a")) ,    
	 ((R "a") : (C "0") : (R "a") : (C "1")) ,    
	 ((R "a") : (C "0") : (R "a") : (C "1") : R "a") ,    
	 ((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "5") .
eq mconf2 = R "a",
	(R "a" : C "0") , 
	(R "a" : C "0" : R "a") , 
	(R "a" : C "0" : R "a" : C "2") .
	 
op mhconf : -> HistoryConfs .
eq mhconf = empty .

op mltss : ->  LtsState .
eq mltss = (LTSS sm mconf mhconf anyevent : "e1") .






op mstates2 : -> Verts .
eq mstates2 = R "a" ,    
	((R "a") : (C "0")) , 
	((R "a") : (C "0") : (R "a")),
	((R "a") : (C "0") : (R "a") : (C "2")) , 
	((R "a") : (C "0") : (R "a") : (C "3")) , 
	((R "a") : (C "0") : (R "a") : (C "3") : (R "a")) , 
	((R "a") : (C "0") : (R "a") : (C "3") : (R "a") : (C "9")) , 
	((R "a") : (C "0") : (R "a") : (C "3") : (R "a") : (C "10")) , 
	((R "a") : (C "0") : (R "a") : (C "3") : (R "b")) , 
	((R "a") : (C "0") : (R "a") : (C "3") : (R "b") : (C "11")) , 	
	((R "a") : (C "0") : (R "a") : (C "3") : (R "b") : (C "12")) 	
	.
	
op mtrans2 : -> Transitions .
eq mtrans2 = (
	*** t16
    (((R "a") : (C "0") : (R "a") : (C "2"))
    	anyevent : "e1" Gd ac0 ac0 ac0 
	((R "a") : (C "0") : (R "a") : (C "3") : (R "a") : (C "9"))
	((R "a") : (C "0") : (R "a"))) ,      
	*** t9
    (((R "a") : (C "0") : (R "a") : (C "2"))
    	anyevent : "e2" Gd ac0 ac0 ac0 
	(((R "a") : (C "0") : (R "a") : (C "3") : (R "a") : (C "9")) ,    
		((R "a") : (C "0") : (R "a") : (C "3") : (R "b") : (C "11")))
	((R "a") : (C "0") : (R "a"))) , 
	*** t8
    ((((R "a") : (C "0") : (R "a") : (C "3") : (R "a") : (C "10")) ,    
		((R "a") : (C "0") : (R "a") : (C "3") : (R "b") : (C "12")))
    	anyevent : "e1" Gd ac0 ac0 ac0 
	((R "a") : (C "0") : (R "a") : (C "2"))	
	((R "a") : (C "0") : (R "a"))) , 
	*** t19
    (((R "a") : (C "0") : (R "a") : (C "3") : (R "a") : (C "9"))
	anyevent : "e1" Gd ac0 ac0 ac0  
	((R "a") : (C "0") : (R "a") : (C "3") : (R "a") : (C "10"))
	((R "a") : (C "0") : (R "a") : (C "3") : (R "a"))) , 
	*** t20
    (((R "a") : (C "0") : (R "a") : (C "3") : (R "b") : (C "11"))
	anyevent : "e1" Gd ac0 ac0 ac0  
	((R "a") : (C "0") : (R "a") : (C "3") : (R "b") : (C "12"))
        ((R "a") : (C "0") : (R "a") : (C "3") : (R "b"))) 
    ) .
    
op mdefs2 : -> Defaults .
eq mdefs2 = 
	 (((R "a") : (C "0") : (R "a")) default 
	 ((R "a") : (C "0") : (R "a") : (C "2"))) , 
	 (((R "a") : (C "0") : (R "a") : (C "3") : (R "b")) default
	 ((R "a") : (C "0") : (R "a") : (C "3") : (R "b") : (C "12"))) .

op sm2 : -> StateMachine .
eq sm2 = (SM mstates2 mdefs2 msdefs mddefs mtrans2) .
	 
op mltss2 : ->  LtsState .
eq mltss2 = (LTSS sm2 mconf2 mhconf anyevent : "e1") .

	



op mstates3 : -> Verts .
eq mstates3 = R "a" ,    
	((R "a") : (C "0")) , 
	((R "a") : (C "0") : (R "a")) , 
	((R "a") : (C "0") : (R "a") : (C "1")) ,    
	((R "a") : (C "0") : (R "a") : (C "1") : R "a") ,    
	((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "5") , 
	((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "6") ,    
	((R "a") : (C "0") : (R "a") : (C "1") : R "a" : F "f") , 
	((R "a") : (C "0") : (R "a") : (C "1") : R "a" : H) , 
	((R "a") : (C "0") : (R "a") : (C "1") : R "a" : H*) , 
	((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "6" : R "a") , 
	((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "6" : R "a" : C "7") , 
	((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "6" : R "a" : C "8") , 
	((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "6" : R "a" : H*) , 
	((R "a") : (C "0") : (R "a") : (C "2")) .
	
op mtrans3 : -> Transitions .
eq mtrans3 = (
	*** t2
    (((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "5")  
	anyevent : "e1" Gd ac0 ac0 ac0 
	((R "a") : (C "0") : (R "a") : (C "1") : R "a" : F "f")
	((R "a") : (C "0") : (R "a") : (C "1") : R "a")) , 
	*** t26
    (((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "5")  
	anyevent : "e1" Gd ac0 ac0 ac0 
	((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "6")
	((R "a") : (C "0") : (R "a") : (C "1") : R "a")) , 
	*** t1
    (((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "6")  
	anyevent : "e1" Gd ac0 ac0 ac0 
	((R "a") : (C "0") : (R "a") : (C "1") : R "a" : F "f")
	((R "a") : (C "0") : (R "a") : (C "1") : R "a")) , 
	*** t15
    (((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "6" : R "a" : C "7")  
	anyevent : "e1" Gd ac0 ac0 ac0 
	((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "6" : R "a" : C "8")
	((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "6" : R "a")) , 
	*** t3
    (((R "a") : (C "0") : (R "a") : (C "2"))
    	anyevent : "e1" Gd ac0 ac0 ac0 
	((R "a") : (C "0") : (R "a") : (C "1"))
	((R "a") : (C "0") : (R "a"))) ,      
	*** t24
    (((R "a") : (C "0") : (R "a") : (C "1"))
    	anyevent : "e1" Gd ac0 ac0 ac0 
	((R "a") : (C "0") : (R "a") : (C "2"))
	((R "a") : (C "0") : (R "a"))) , 
	*** t22   
    ((((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "6" : R "a" : C "8"))
    	anyevent : "e1" Gd ac0 ac0 ac0 
	((R "a") : (C "0") : (R "a") : (C "2"))
	((R "a") : (C "0") : (R "a"))) ,      
	***t17
    (((R "a") : (C "0") : (R "a") : (C "2"))
    	anyevent : "esh" Gd ac0 ac0 ac0  
	((R "a") : (C "0") : (R "a") : (C "1") : R "a" : H)
	((R "a") : (C "0") : (R "a"))) , 
	***t18
    (((R "a") : (C "0") : (R "a") : (C "2"))
    	anyevent : "edh" Gd ac0 ac0 ac0  
	((R "a") : (C "0") : (R "a") : (C "1") : R "a" : H*)
	((R "a") : (C "0") : (R "a"))) 
	***t25
					

    ) .
    
op mdefs3 : -> Defaults .
eq mdefs3 = (((R "a") : (C "0") : (R "a") : (C "1") : R "a") default 
		((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "5")) , 
	(((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "6" : R "a") 
		default 
		((R "a") : (C "0") : (R "a") : (C "1") : R "a" : C "6" : R "a" : C "7")) , 
	 (((R "a") : (C "0") : (R "a")) default 
	 ((R "a") : (C "0") : (R "a") : (C "2"))) 
	 	
	  .

op sm3 : -> StateMachine .
eq sm3 = (SM mstates mdefs msdefs mddefs mtrans) .

op mconf3 : -> Verts .
eq mconf3 = R "a" , 
	(R "a" : C "0") , 
	(R "a" : C "0" : R "a") , 
	(R "a" : C "0" : R "a" : C "2") .
	 
op mltss3 : ->  LtsState .
eq mltss3 = (LTSS sm3 mconf3 mhconf anyevent : "e1") .

endm