/*! \file sc.c 
 *
 * Main file for using SyncChart C macros
 *
 * See README.txt for general information.
 * See LICENSE.txt for licensing information.
 * For further information, see
 * http://www.informatik.uni-kiel.de/rtsys/sc/ .
 *
 * @author Reinhard v. Hanxleden,
 * rvh@informatik.uni-kiel.de
 */

#include "sc-generic.h"

// ===================================================================
//! The main program
/*! Returns 0 iff outputs generated by program match reference trace
 */
int main()
{
  int runCnt;               // Counts program runs
  int tickCnt;              // Counts program ticks
  int runInstrCnt;          // Instructions in one run
  int runsInstrCnt = 0;     // Instructions accumulated over all runs
  int outputsOK = 1;        // Outputs of simulation correct?
  int notDone;              // Automaton still running?
  int i, ok;
  int sigsetSize = _sigMax / _setPartSize + 1;

  // Execute all runs
  for (runCnt = 0; (runCnt < _runMax) && outputsOK; runCnt++) {
    printf("#### RUN %d STARTS ##################################\n",	
	   runCnt);

    runInstrCnt = 0;
    tickCnt = 0;
    RESET();                         // Reset automaton

    do {                             // Execute all ticks of one run
      tickInstrCnt = 0;
      getInputs(runCnt, tickCnt);

      for (i = 0; i < sigsetSize; i++) {
	tickInputsPtr[i] = signalsPtr[i];
      }

      trace2("==== TICK %d STARTS, inputs = %s",
	     tickCnt, _sigPtr2str(tickInputsPtr));
      if (tickCnt != 0) {
	printf(", enabled = %s", _idPtr2str2(enabledPtr));
      }
      sig2names("\n==== Inputs (id/name): ", "\n", tickInputsPtr);
      if (tickCnt != 0) {
	id2names("==== Enabled (id/state): ", "\n", enabledPtr);
      }

      notDone = tick();             // Call automaton function
      runInstrCnt += tickInstrCnt;
      trace2("==== TICK %d terminates after %d instructions.\n",
	     tickCnt, tickInstrCnt);
      id2names("==== Enabled (id/state): ", "\n", enabledPtr);
      sig2names("==== Resulting signals (name/id): ", "", signalsPtr);
      outputsOK = checkOutputs(runCnt, tickCnt, tickOutputsPtr);
      if (outputsOK) {

	for (i = 0; i < sigsetSize; i++) {
	  tickSignalsPtr[i] = tickInputsPtr[i] | tickOutputsPtr[i];
	}
	for (ok = 1, i = 0; ok && (i < sigsetSize); i++) {
	  ok = (signalsPtr[i] == tickSignalsPtr[i]);
	}
	if (ok) {
	  trace0(", Outputs OK.\n\n");
	} else {
	  sig2names(", Outputs NOT OK - expected signals ", "!!\n\n",
		 tickSignalsPtr);
	  outputsOK = 0;
	}
      } else {
	notDone = 0;
      }

      tickCnt++;
      if (tickCnt >= _tickMax) {
	printf("==== Executed _tickMax = %d ticks, terminate.\n", _tickMax);
	notDone = 0;
      }

    } while (notDone && outputsOK);
    
    printf("#### RUN %d terminates after %d instructions\n\n",
	   runCnt, runInstrCnt);					
    runsInstrCnt += runInstrCnt;
  };

  printf("#### All runs terminate, after %d instructions\n\n", runsInstrCnt);					
  return !outputsOK;
}
