<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dependency"
    nsURI="http://kieler.cs.cau.de/dependency/0.1.0" nsPrefix="dependency">
  <eClassifiers xsi:type="ecore:EClass" name="StateAndTransition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" eType="ecore:EClass ../../de.cau.cs.kieler.synccharts/model/synccharts.ecore#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" eType="ecore:EClass ../../de.cau.cs.kieler.synccharts/model/synccharts.ecore#//Transition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dependency">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//StateAndTransition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" eType="#//StateAndTransition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SignalDependency" eSuperTypes="#//Dependency"/>
  <eClassifiers xsi:type="ecore:EClass" name="HierarchyDependency" eSuperTypes="#//Dependency"/>
  <eClassifiers xsi:type="ecore:EClass" name="ControlflowDependency" eSuperTypes="#//Dependency"/>
  <eClassifiers xsi:type="ecore:EClass" name="TransitionDependency" eSuperTypes="#//Dependency"/>
</ecore:EPackage>
