<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="scl" nsURI="http://kieler.cs.cau.de/scl/0.2.0" nsPrefix="scl">
  <eClassifiers xsi:type="ecore:EClass" name="SCLProgram" eSuperTypes="../../de.cau.cs.kieler.annotations/model/annotations.ecore#//Pragmatable ../../de.cau.cs.kieler.annotations/model/annotations.ecore#//Nameable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modules" lowerBound="1"
        upperBound="-1" eType="#//Module" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module" eSuperTypes="#//Scope ../../de.cau.cs.kieler.annotations/model/annotations.ecore#//NamedObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true" eSuperTypes="../../de.cau.cs.kieler.annotations/model/annotations.ecore#//Annotatable #//SequencePart"/>
  <eClassifiers xsi:type="ecore:EClass" name="StatementContainer" abstract="true"
      eSuperTypes="../../de.cau.cs.kieler.annotations/model/annotations.ecore#//Annotatable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scope" abstract="true" eSuperTypes="../../de.cau.cs.kieler.annotations/model/annotations.ecore#//Annotatable ../../de.cau.cs.kieler.kexpressions/model/kext.ecore#//DeclarationScope #//StatementContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="Pause" eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Label" eSuperTypes="#//Statement ../../de.cau.cs.kieler.annotations/model/annotations.ecore#//NamedObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="Goto" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Label"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assignment" eSuperTypes="../../de.cau.cs.kieler.kexpressions/model/keffects.ecore#//Assignment #//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Conditional" eSuperTypes="#//Scope #//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass ../../de.cau.cs.kieler.kexpressions/model/kexpressions.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="#//Scope"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parallel" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="threads" upperBound="-1"
        eType="#//Thread" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleCall" eSuperTypes="../../de.cau.cs.kieler.kexpressions/model/kexpressions.ecore#//Call #//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" lowerBound="1"
        eType="#//Module"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Thread" eSuperTypes="#//Scope"/>
  <eClassifiers xsi:type="ecore:EClass" name="ScopeStatement" eSuperTypes="#//Statement #//Scope"/>
  <eClassifiers xsi:type="ecore:EClass" name="ElseScope" eSuperTypes="#//Scope #//SequencePart"/>
  <eClassifiers xsi:type="ecore:EClass" name="SequencePart" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semicolon" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
</ecore:EPackage>
