<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="scl" nsURI="http://kieler.cs.cau.de/scl/0.2.0" nsPrefix="scl">
  <eClassifiers xsi:type="ecore:EClass" name="SCLProgram" eSuperTypes="#//Scope">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true" eSuperTypes="../../de.cau.cs.kieler.annotations/model/annotations.ecore#//Annotatable"/>
  <eClassifiers xsi:type="ecore:EClass" name="StatementContainer" abstract="true"
      eSuperTypes="../../de.cau.cs.kieler.annotations/model/annotations.ecore#//Annotatable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scope" abstract="true" eSuperTypes="../../de.cau.cs.kieler.annotations/model/annotations.ecore#//Annotatable #//StatementContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" upperBound="-1"
        eType="ecore:EClass ../../de.cau.cs.kieler.kexpressions/model/kexpressions.ecore#//Declaration"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pause" eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Label" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Goto" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Label"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assignment" eSuperTypes="../../de.cau.cs.kieler.kexpressions/model/keffects.ecore#//Assignment #//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Conditional" eSuperTypes="#//Scope #//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass ../../de.cau.cs.kieler.kexpressions/model/kexpressions.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="#//Scope"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parallel" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="threads" upperBound="-1"
        eType="#//Thread" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Thread" eSuperTypes="#//Scope"/>
  <eClassifiers xsi:type="ecore:EClass" name="ScopeStatement" eSuperTypes="#//Statement #//Scope"/>
  <eClassifiers xsi:type="ecore:EClass" name="ElseScope" eSuperTypes="#//Scope"/>
</ecore:EPackage>
