<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tracingtree" nsURI="http://kieler.cs.cau.de/tracingtree/0.1.0"
    nsPrefix="tracingtree">
  <eClassifiers xsi:type="ecore:EClass" name="ModelWrapper">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract representation of a model used in a transformation.&#xA;&lt;p>&#xA;Used as nodes in tree structure."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelTypeID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Unique ID for type of represented model in transformation"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelObjects" lowerBound="1"
        upperBound="-1" eType="#//EObjectWrapper" containment="true" eOpposite="#//EObjectWrapper/model">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="All elements contained byrepresented model."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetTransformations"
        upperBound="-1" eType="#//ModelTransformation" containment="true" eOpposite="#//ModelTransformation/source">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List of model-transformations were this model is source model."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceTransformation" eType="#//ModelTransformation"
        eOpposite="#//ModelTransformation/target">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Model-transformations were this model is target model."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transient" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This flag is set if model's elemets have no {@link Element#referencedObject referencedObject} entry.&#xA;&lt;p>&#xA;Falg status must be consistent with all elements."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootObject" lowerBound="1"
        eType="#//EObjectWrapper">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Reference to element which represents root element of the represented model."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EObjectWrapper">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract representation of a object in a model."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="#//ModelWrapper"
        eOpposite="#//ModelWrapper/modelObjects">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="ModelWrapper for model containing this EObject."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Display name of the referenced object.&#xA;&lt;p>&#xA;This string should enable a identification of the object even if no intance is referenced."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetTransformations"
        upperBound="-1" eType="#//EObjectTransformation" eOpposite="#//EObjectTransformation/source">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List of object-transformations were this object is source element."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceTransformations"
        upperBound="-1" eType="#//EObjectTransformation" eOpposite="#//EObjectTransformation/target">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List of object-transformations were this object is target element."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eObject" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Reference to a instance of wrapped EObject&#xA;&lt;p>&#xA;This reference is mandatory iff transient flag of model owning this element is NOT set."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelTransformation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Transformation relation between two models.&#xA;&lt;p>&#xA;Used as edges in tree structure."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transformationID" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral="">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Unique identifier of this transformation."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//ModelWrapper" eOpposite="#//ModelWrapper/targetTransformations">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Source model of this transfromation."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//ModelWrapper" containment="true" eOpposite="#//ModelWrapper/sourceTransformation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Target model of this transfromation."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectTransformations"
        lowerBound="1" upperBound="-1" eType="#//EObjectTransformation" containment="true"
        eOpposite="#//EObjectTransformation/modelTransformation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="All object-transformations which are part of this model-transformation"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EObjectTransformation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Transformation relation between two elements."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelTransformation" lowerBound="1"
        eType="#//ModelTransformation" eOpposite="#//ModelTransformation/objectTransformations">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Model-transformation were this element-tranformation is part of."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//EObjectWrapper" eOpposite="#//EObjectWrapper/targetTransformations">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Source object of this transfromation."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//EObjectWrapper" eOpposite="#//EObjectWrapper/sourceTransformations">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Target object of this transfromation."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
