<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="esterel"
    nsURI="http://www.cau.de/cs/kieler/kies/Esterel" nsPrefix="esterel">
  <eClassifiers xsi:type="ecore:EClass" name="Program">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modules" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Module"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//ModuleInterface"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//ModuleBody"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleInterface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="intSignalDecls" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//InterfaceSignalDecl"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intTypeDecls" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//TypeDecl"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intSensorDecls" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//SensorDecl"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intConstantDecls" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//ConstantDecls"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intRelationDecls" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//RelationDecl"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intTaskDecls" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//TaskDecl"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intFunctionDecls" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//FunctionDecl"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intProcedureDecls" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//ProcedureDecl"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChannelDescription" eSuperTypes="platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ChannelDescription"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypeIdentifier" eSuperTypes="platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//TypeIdentifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="LocalSignalDecl" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signalList" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//LocalSignalList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalSignalList"/>
  <eClassifiers xsi:type="ecore:EClass" name="SensorDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensors" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//SensorWithType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SensorWithType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensor" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ISignal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//TypeIdentifier"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationDecl"/>
  <eClassifiers xsi:type="ecore:EClass" name="RelationType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationImplication" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//RelationType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="first" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ISignal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="second" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ISignal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationIncompatibility" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//RelationType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomp" unique="false"
        upperBound="-1" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ISignal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Type"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstantDecls">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constants" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//OneTypeConstantDecls"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OneTypeConstantDecls">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constants" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//ConstantWithValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//TypeIdentifier"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstantWithValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constant" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ValuedObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="functions" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Function"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="idList" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//TypeIdentifier"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//TypeIdentifier"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcedureDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="procedures" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Procedure"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Procedure">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="idList1" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//TypeIdentifier"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="idList2" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//TypeIdentifier"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Task"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="idList1" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//TypeIdentifier"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="idList2" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//TypeIdentifier"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assignment" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="var" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//IVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Abort" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbortBody"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbortInstance" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//AbortBody platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//WeakAbortBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="delay" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//DelayExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbortCase" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//AbortBody platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//WeakAbortBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cases" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//AbortCaseSingle"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbortCaseSingle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="delay" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//DelayExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WeakAbortBody"/>
  <eClassifiers xsi:type="ecore:EClass" name="WeakAbortEnd">
    <eStructuralFeatures xsi:type="ecore:EReference" name="optEnd" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//WeakAbortEndAlt"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WeakAbortEndAlt">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endA" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Await" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//AwaitBody"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AwaitBody">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AwaitInstance" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//AwaitBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="delay" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//DelayExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AwaitCase" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//AwaitBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cases" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//AbortCaseSingle"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcCall" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="proc" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Procedure"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="varList" unique="false"
        upperBound="-1" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//IVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="kexpressions" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Do" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoUpto">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//DelayExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoWatching">
    <eStructuralFeatures xsi:type="ecore:EReference" name="delay" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//DelayExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//DoWatchingEnd"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoWatchingEnd">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Emit" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ISignal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tick" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EveryDo" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="delay" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//DelayExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Exit" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trap" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//TrapDecl"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Halt" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="IfTest" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenPart" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//ThenPart"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elsif" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//ElsIf"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elsePart" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//ElsePart"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElsIf">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenPart" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//ThenPart"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ThenPart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElsePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Loop" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//LoopBody"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end1" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//EndLoop"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//LoopEach"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EndLoop">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endOpt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoopEach"/>
  <eClassifiers xsi:type="ecore:EClass" name="LoopDelay" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//LoopEach">
    <eStructuralFeatures xsi:type="ecore:EReference" name="delay" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//DelayExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoopBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Nothing" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Pause" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Present" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//PresentBody"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elsePart" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//ElsePart"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PresentBody"/>
  <eClassifiers xsi:type="ecore:EClass" name="PresentEventBody" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//PresentBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//PresentEvent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenPart" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//ThenPart"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PresentCaseList" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//PresentBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cases" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//PresentCase"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PresentCase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//PresentEvent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PresentEvent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tick" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Repeat" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="positive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Run" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//ModuleRenaming"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="list" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//RenamingList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleRenaming">
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Module"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RenamingList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="list" upperBound="-1" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Renaming"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Renaming">
    <eStructuralFeatures xsi:type="ecore:EReference" name="renamings" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeRenaming">
    <eStructuralFeatures xsi:type="ecore:EReference" name="newName" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newType" eType="ecore:EEnum platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ValueType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldName" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstantRenaming">
    <eStructuralFeatures xsi:type="ecore:EReference" name="newName" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ValuedObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldName" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ValuedObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionRenaming">
    <eStructuralFeatures xsi:type="ecore:EReference" name="newName" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Function"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newFunc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldName" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Function"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcedureRenaming">
    <eStructuralFeatures xsi:type="ecore:EReference" name="newName" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Procedure"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldName" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Procedure"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskRenaming">
    <eStructuralFeatures xsi:type="ecore:EReference" name="newName" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Task"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldName" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Task"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SignalRenaming">
    <eStructuralFeatures xsi:type="ecore:EReference" name="newName" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ISignal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldName" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ISignal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Suspend" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="delay" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//DelayExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sustain" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ISignal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tick" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trap" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trapDeclList" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//TrapDeclList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trapHandler" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//TrapHandler"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrapDeclList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trapDecls" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ISignal"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrapHandler">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trapExpr" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalVariable" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="var" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//InterfaceVariableDecl"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DelayExpr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//DelayEvent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isImmediate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DelayEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tick" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Exec" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="task" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Task"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//ExecBody"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="retSignal" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ISignal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="execCaseList" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//ExecCase"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vars" unique="false" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//IVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="kexpressions" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecCase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="task" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Task"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//ExecBody"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="retSignal" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ISignal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EsterelTypeIdentifier" eSuperTypes="platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//TypeIdentifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="func" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Function"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EsterelType" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//TypeIdentifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="estType" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalSignal" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//LocalSignalList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ISignal"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relation" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//RelationDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="relations" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//RelationType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constant" eSuperTypes="platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ValuedObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="Parallel" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="list" upperBound="-1" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sequence" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="list" upperBound="-1" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WeakAbort" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Abort"/>
  <eClassifiers xsi:type="ecore:EClass" name="WeakAbortInstance" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//AbortInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//WeakAbortEnd"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WeakAbortCase" eSuperTypes="platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//AbortCase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//WeakAbortEnd"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrapDecl" eSuperTypes="platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ISignal"/>
  <eClassifiers xsi:type="ecore:EClass" name="TrapExpression" eSuperTypes="platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trap" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ISignal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionExpression" eSuperTypes="platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Function"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="kexpressions" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstantExpression" eSuperTypes="platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constant" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kies/src-gen/de/cau/cs/kieler/kies/Esterel.ecore#//Constant"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrapReferenceExpr" eSuperTypes="platform:/resource/de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ValuedObjectReference"/>
</ecore:EPackage>
