<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="synccharts"
    nsURI="http://www.informatik.uni-kiel.de/rtsys/synccharts" nsPrefix="synccharts">
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stateKind" lowerBound="1"
        eType="#//StateKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stateFlag" lowerBound="1"
        eType="#//StateFlag"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signals" upperBound="-1"
        eType="#//Signal" containment="true" eOpposite="#//Signal/parentState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="regions" upperBound="-1"
        eType="#//Region" containment="true" eOpposite="#//Region/parentState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entryActions" upperBound="-1"
        eType="#//Action" containment="true" eOpposite="#//Action/parentStateEntryAction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="innerActions" upperBound="-1"
        eType="#//Action" containment="true" eOpposite="#//Action/parentStateInnerAction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exitActions" upperBound="-1"
        eType="#//Action" containment="true" eOpposite="#//Action/parentStateExitAction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signalRenamings" upperBound="-1"
        eType="#//SignalRenaming" containment="true" eOpposite="#//SignalRenaming/parentState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="suspensionTrigger" eType="#//SuspensionTrigger"
        containment="true" eOpposite="#//SuspensionTrigger/parentState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingTransitions" upperBound="-1"
        eType="#//Transition" containment="true" eOpposite="#//Transition/sourceState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentRegion" lowerBound="1"
        eType="#//Region" eOpposite="#//Region/innerStates"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//Variable" containment="true" eOpposite="#//Variable/parentState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StateKind">
    <eLiterals name="NORMAL"/>
    <eLiterals name="PSEUDO" value="1"/>
    <eLiterals name="REFERENCE"/>
    <eLiterals name="TEXTUAL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StateFlag">
    <eLiterals name="NORMAL"/>
    <eLiterals name="INITIAL" value="1"/>
    <eLiterals name="FINAL" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Signal" eSuperTypes="#//ValuedObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentState" lowerBound="1"
        eType="#//State" eOpposite="#//State/signals"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isLocal" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isInput" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOutput" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="combineType" lowerBound="1"
        eType="#//CombineType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValuedObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//ValueType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Emission">
    <eStructuralFeatures xsi:type="ecore:EReference" name="newValue" eType="#//Expression"
        containment="true" eOpposite="#//Expression/parentEmisson"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" lowerBound="1"
        eType="#//Signal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentAction" lowerBound="1"
        eType="#//Action" eOpposite="#//Action/emissions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delay" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="immediate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transitionKind" lowerBound="1"
        eType="#//TransitionKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetState" lowerBound="1"
        eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceState" lowerBound="1"
        eType="#//State" eOpposite="#//State/outgoingTransitions"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="history" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TransitionKind">
    <eLiterals name="WEAKABORT" literal="WEAKABORT"/>
    <eLiterals name="STRONGABORT" value="1"/>
    <eLiterals name="NORMALTERMINATION" value="2" literal="NORMALTERMINATION"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentAction" lowerBound="1"
        eType="#//Action" eOpposite="#//Action/trigger"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentEmisson" lowerBound="1"
        eType="#//Emission" eOpposite="#//Emission/newValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentAssignment" lowerBound="1"
        eType="#//Assignment" eOpposite="#//Assignment/expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentExpression" lowerBound="1"
        eType="#//ComplexExpression" eOpposite="#//ComplexExpression/subExpressions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentSuspensionTrigger"
        lowerBound="1" eType="#//SuspensionTrigger" eOpposite="#//SuspensionTrigger/expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SignalRenaming">
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldSignal" lowerBound="1"
        eType="#//Signal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newSignal" lowerBound="1"
        eType="#//Signal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentState" lowerBound="1"
        eType="#//State" eOpposite="#//State/signalRenamings"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operatorKind" lowerBound="1"
        eType="#//OperatorKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentExpression" lowerBound="1"
        eType="#//ComplexExpression" eOpposite="#//ComplexExpression/operator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OperatorKind">
    <eLiterals name="NOT" literal="NOT"/>
    <eLiterals name="EQ" value="1" literal="EQ"/>
    <eLiterals name="LT" value="2"/>
    <eLiterals name="LEQ" value="3"/>
    <eLiterals name="AND" value="4"/>
    <eLiterals name="OR" value="5"/>
    <eLiterals name="ADD" value="6"/>
    <eLiterals name="SUB" value="7"/>
    <eLiterals name="MULT" value="8"/>
    <eLiterals name="DIV" value="9"/>
    <eLiterals name="VAL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="emissions" upperBound="-1"
        eType="#//Emission" containment="true" eOpposite="#//Emission/parentAction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" eType="#//Expression"
        containment="true" eOpposite="#//Expression/parentAction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentStateEntryAction"
        lowerBound="1" eType="#//State" eOpposite="#//State/entryActions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignments" upperBound="-1"
        eType="#//Assignment" containment="true" eOpposite="#//Assignment/parentAction"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="triggersAndEffects" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentStateInnerAction"
        lowerBound="1" eType="#//State" eOpposite="#//State/innerActions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentStateExitAction"
        lowerBound="1" eType="#//State" eOpposite="#//State/exitActions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SuspensionTrigger">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentState" lowerBound="1"
        eType="#//State" eOpposite="#//State/suspensionTrigger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="immediate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="trigger" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true" eOpposite="#//Expression/parentSuspensionTrigger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assignment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentAction" eType="#//Action"
        eOpposite="#//Action/assignments"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true" eOpposite="#//Expression/parentAssignment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//ValuedObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentState" eType="#//State"
        eOpposite="#//State/variables"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Region">
    <eStructuralFeatures xsi:type="ecore:EReference" name="innerStates" upperBound="-1"
        eType="#//State" containment="true" eOpposite="#//State/parentRegion"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentState" eType="#//State"
        eOpposite="#//State/regions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operator" lowerBound="1"
        eType="#//Operator" containment="true" eOpposite="#//Operator/parentExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subExpressions" lowerBound="1"
        upperBound="2" eType="#//Expression" containment="true" eOpposite="#//Expression/parentExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CombineType">
    <eLiterals name="NONE" literal="NONE"/>
    <eLiterals name="ADD" value="1" literal="ADD"/>
    <eLiterals name="MULT" value="2" literal="MULT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SignalReference" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" lowerBound="1"
        eType="#//Signal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableReference" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ValueType">
    <eLiterals name="PURE"/>
    <eLiterals name="BOOL" value="1"/>
    <eLiterals name="UNSIGNED" value="2"/>
    <eLiterals name="INTEGER" value="3"/>
    <eLiterals name="DOUBLE" value="4"/>
  </eClassifiers>
</ecore:EPackage>
