/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_cau_cs_kieler_krep_evalbench_comm_KepWrapper */

#ifndef _Included_de_cau_cs_kieler_krep_evalbench_comm_KepWrapper
#define _Included_de_cau_cs_kieler_krep_evalbench_comm_KepWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_cau_cs_kieler_krep_evalbench_comm_KepWrapper
 * Method:    kep_step
 * Signature: (Ljava/lang/String;)B
 */
JNIEXPORT jbyte JNICALL Java_de_cau_cs_kieler_krep_evalbench_comm_KepWrapper_kep_1step
  (JNIEnv *, jclass, jstring);

/*
 * Class:     de_cau_cs_kieler_krep_evalbench_comm_KepWrapper
 * Method:    kep_recv
 * Signature: (Ljava/lang/String;)B
 */
JNIEXPORT jbyte JNICALL Java_de_cau_cs_kieler_krep_evalbench_comm_KepWrapper_kep_1recv
  (JNIEnv *, jclass, jstring);

/*
 * Class:     de_cau_cs_kieler_krep_evalbench_comm_KepWrapper
 * Method:    kep_reset
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_cau_cs_kieler_krep_evalbench_comm_KepWrapper_kep_1reset
  (JNIEnv *, jclass, jstring);

/*
 * Class:     de_cau_cs_kieler_krep_evalbench_comm_KepWrapper
 * Method:    kep_send
 * Signature: (BLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_cau_cs_kieler_krep_evalbench_comm_KepWrapper_kep_1send
  (JNIEnv *, jclass, jbyte, jstring);

#ifdef __cplusplus
}
#endif
#endif
