/*
* generated by Xtext
*/
package de.cau.cs.kieler.synccharts.text.actions.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class ActionsOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
