<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="kits"
    nsURI="http://www.cau.de/cs/kieler/synccharts/dsl/Kits" nsPrefix="kits">
  <eClassifiers xsi:type="ecore:EClass" name="Region">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.synccharts/model/synccharts.ecore#//Variable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signals" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.synccharts/model/synccharts.ecore#//Signal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="innerStates" upperBound="-1"
        eType="#//State" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isInitial" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isFinal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EEnum platform:/resource/de.cau.cs.kieler.synccharts/model/synccharts.ecore#//StateType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bodyText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entryActions" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.synccharts/model/synccharts.ecore#//Action"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="innerActions" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.synccharts/model/synccharts.ecore#//Action"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exitActions" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.synccharts/model/synccharts.ecore#//Action"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="suspensionTrigger" eType="ecore:EClass platform:/resource/de.cau.cs.kieler.synccharts/model/synccharts.ecore#//Action"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signals" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.synccharts/model/synccharts.ecore#//Signal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="regions" upperBound="-1"
        eType="#//Region" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingTransitions" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.synccharts/model/synccharts.ecore#//Transition"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
