/*
 * generated by Xtext
 */
package de.cau.cs.kieler.sccharts.text3.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import de.cau.cs.kieler.sccharts.text3.services.Sct3GrammarAccess;

public class Sct3Parser extends AbstractContentAssistParser {
	
	@Inject
	private Sct3GrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected de.cau.cs.kieler.sccharts.text3.ui.contentassist.antlr.internal.InternalSct3Parser createParser() {
		de.cau.cs.kieler.sccharts.text3.ui.contentassist.antlr.internal.InternalSct3Parser result = new de.cau.cs.kieler.sccharts.text3.ui.contentassist.antlr.internal.InternalSct3Parser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getRootStateAccess().getAlternatives_7(), "rule__RootState__Alternatives_7");
					put(grammarAccess.getStateAccess().getAlternatives_7_3(), "rule__State__Alternatives_7_3");
					put(grammarAccess.getTransitionAccess().getAlternatives_6(), "rule__Transition__Alternatives_6");
					put(grammarAccess.getLocalActionAccess().getAlternatives(), "rule__LocalAction__Alternatives");
					put(grammarAccess.getRegionAccess().getAlternatives(), "rule__Region__Alternatives");
					put(grammarAccess.getAtomicExpressionAccess().getAlternatives(), "rule__AtomicExpression__Alternatives");
					put(grammarAccess.getTestEntityAccess().getAlternatives(), "rule__TestEntity__Alternatives");
					put(grammarAccess.getDeclarationAccess().getAlternatives(), "rule__Declaration__Alternatives");
					put(grammarAccess.getDeclarationWOSemicolonAccess().getAlternatives(), "rule__DeclarationWOSemicolon__Alternatives");
					put(grammarAccess.getVariableDeclarationAccess().getAlternatives_5(), "rule__VariableDeclaration__Alternatives_5");
					put(grammarAccess.getVariableDeclarationWOSemicolonAccess().getAlternatives(), "rule__VariableDeclarationWOSemicolon__Alternatives");
					put(grammarAccess.getEffectAccess().getAlternatives(), "rule__Effect__Alternatives");
					put(grammarAccess.getFunctionCallEffectAccess().getAlternatives_3(), "rule__FunctionCallEffect__Alternatives_3");
					put(grammarAccess.getExpressionAccess().getAlternatives(), "rule__Expression__Alternatives");
					put(grammarAccess.getNotOrValuedExpressionAccess().getAlternatives(), "rule__NotOrValuedExpression__Alternatives");
					put(grammarAccess.getNotExpressionAccess().getAlternatives(), "rule__NotExpression__Alternatives");
					put(grammarAccess.getNegExpressionAccess().getAlternatives(), "rule__NegExpression__Alternatives");
					put(grammarAccess.getAtomicValuedExpressionAccess().getAlternatives(), "rule__AtomicValuedExpression__Alternatives");
					put(grammarAccess.getValuedObjectTestExpressionAccess().getAlternatives(), "rule__ValuedObjectTestExpression__Alternatives");
					put(grammarAccess.getValuedObjectTestExpressionAccess().getOperatorAlternatives_0_1_0(), "rule__ValuedObjectTestExpression__OperatorAlternatives_0_1_0");
					put(grammarAccess.getFunctionCallAccess().getAlternatives_2(), "rule__FunctionCall__Alternatives_2");
					put(grammarAccess.getAnyTypeAccess().getAlternatives(), "rule__AnyType__Alternatives");
					put(grammarAccess.getAnnotationAccess().getAlternatives(), "rule__Annotation__Alternatives");
					put(grammarAccess.getValuedAnnotationAccess().getAlternatives(), "rule__ValuedAnnotation__Alternatives");
					put(grammarAccess.getRestrictedTypeAnnotationAccess().getAlternatives(), "rule__RestrictedTypeAnnotation__Alternatives");
					put(grammarAccess.getQuotedStringAnnotationAccess().getAlternatives(), "rule__QuotedStringAnnotation__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getEStringBooleanAccess().getAlternatives(), "rule__EStringBoolean__Alternatives");
					put(grammarAccess.getEStringAllTypesAccess().getAlternatives(), "rule__EStringAllTypes__Alternatives");
					put(grammarAccess.getTransitionTypeAccess().getAlternatives(), "rule__TransitionType__Alternatives");
					put(grammarAccess.getHistoryTypeAccess().getAlternatives(), "rule__HistoryType__Alternatives");
					put(grammarAccess.getAssignOperatorAccess().getAlternatives(), "rule__AssignOperator__Alternatives");
					put(grammarAccess.getPostfixOperatorAccess().getAlternatives(), "rule__PostfixOperator__Alternatives");
					put(grammarAccess.getCompareOperatorAccess().getAlternatives(), "rule__CompareOperator__Alternatives");
					put(grammarAccess.getValueTypeAccess().getAlternatives(), "rule__ValueType__Alternatives");
					put(grammarAccess.getCombineOperatorAccess().getAlternatives(), "rule__CombineOperator__Alternatives");
					put(grammarAccess.getRootStateAccess().getGroup(), "rule__RootState__Group__0");
					put(grammarAccess.getStateAccess().getGroup(), "rule__State__Group__0");
					put(grammarAccess.getStateAccess().getGroup_7(), "rule__State__Group_7__0");
					put(grammarAccess.getTransitionAccess().getGroup(), "rule__Transition__Group__0");
					put(grammarAccess.getTransitionAccess().getGroup_6_0(), "rule__Transition__Group_6_0__0");
					put(grammarAccess.getTransitionAccess().getGroup_6_0_0(), "rule__Transition__Group_6_0_0__0");
					put(grammarAccess.getTransitionAccess().getGroup_6_0_1(), "rule__Transition__Group_6_0_1__0");
					put(grammarAccess.getTransitionAccess().getGroup_6_0_1_2(), "rule__Transition__Group_6_0_1_2__0");
					put(grammarAccess.getTransitionAccess().getGroup_6_1(), "rule__Transition__Group_6_1__0");
					put(grammarAccess.getEntryActionAccess().getGroup(), "rule__EntryAction__Group__0");
					put(grammarAccess.getEntryActionAccess().getGroup_2(), "rule__EntryAction__Group_2__0");
					put(grammarAccess.getEntryActionAccess().getGroup_3(), "rule__EntryAction__Group_3__0");
					put(grammarAccess.getEntryActionAccess().getGroup_3_2(), "rule__EntryAction__Group_3_2__0");
					put(grammarAccess.getDuringActionAccess().getGroup(), "rule__DuringAction__Group__0");
					put(grammarAccess.getDuringActionAccess().getGroup_3(), "rule__DuringAction__Group_3__0");
					put(grammarAccess.getDuringActionAccess().getGroup_4(), "rule__DuringAction__Group_4__0");
					put(grammarAccess.getDuringActionAccess().getGroup_4_2(), "rule__DuringAction__Group_4_2__0");
					put(grammarAccess.getExitActionAccess().getGroup(), "rule__ExitAction__Group__0");
					put(grammarAccess.getExitActionAccess().getGroup_2(), "rule__ExitAction__Group_2__0");
					put(grammarAccess.getExitActionAccess().getGroup_3(), "rule__ExitAction__Group_3__0");
					put(grammarAccess.getExitActionAccess().getGroup_3_2(), "rule__ExitAction__Group_3_2__0");
					put(grammarAccess.getSuspendActionAccess().getGroup(), "rule__SuspendAction__Group__0");
					put(grammarAccess.getSuspendActionAccess().getGroup_4(), "rule__SuspendAction__Group_4__0");
					put(grammarAccess.getIterateActionAccess().getGroup(), "rule__IterateAction__Group__0");
					put(grammarAccess.getIterateActionAccess().getGroup_3(), "rule__IterateAction__Group_3__0");
					put(grammarAccess.getIterateActionAccess().getGroup_4(), "rule__IterateAction__Group_4__0");
					put(grammarAccess.getIterateActionAccess().getGroup_4_2(), "rule__IterateAction__Group_4_2__0");
					put(grammarAccess.getInitActionAccess().getGroup(), "rule__InitAction__Group__0");
					put(grammarAccess.getInitActionAccess().getGroup_2(), "rule__InitAction__Group_2__0");
					put(grammarAccess.getInitActionAccess().getGroup_3(), "rule__InitAction__Group_3__0");
					put(grammarAccess.getInitActionAccess().getGroup_3_2(), "rule__InitAction__Group_3_2__0");
					put(grammarAccess.getFinalActionAccess().getGroup(), "rule__FinalAction__Group__0");
					put(grammarAccess.getFinalActionAccess().getGroup_2(), "rule__FinalAction__Group_2__0");
					put(grammarAccess.getFinalActionAccess().getGroup_3(), "rule__FinalAction__Group_3__0");
					put(grammarAccess.getFinalActionAccess().getGroup_3_2(), "rule__FinalAction__Group_3_2__0");
					put(grammarAccess.getSingleControlflowRegionAccess().getGroup(), "rule__SingleControlflowRegion__Group__0");
					put(grammarAccess.getSingleDataflowRegionAccess().getGroup(), "rule__SingleDataflowRegion__Group__0");
					put(grammarAccess.getControlflowRegionAccess().getGroup(), "rule__ControlflowRegion__Group__0");
					put(grammarAccess.getDataflowRegionAccess().getGroup(), "rule__DataflowRegion__Group__0");
					put(grammarAccess.getDFAssignmentAccess().getGroup(), "rule__DFAssignment__Group__0");
					put(grammarAccess.getDFAssignmentAccess().getGroup_2(), "rule__DFAssignment__Group_2__0");
					put(grammarAccess.getEquationAccess().getGroup(), "rule__Equation__Group__0");
					put(grammarAccess.getEquationAccess().getGroup_1(), "rule__Equation__Group_1__0");
					put(grammarAccess.getBindingAccess().getGroup(), "rule__Binding__Group__0");
					put(grammarAccess.getAtomicExpressionAccess().getGroup_2(), "rule__AtomicExpression__Group_2__0");
					put(grammarAccess.getScopeAccess().getGroup(), "rule__Scope__Group__0");
					put(grammarAccess.getScopeAccess().getGroup_1(), "rule__Scope__Group_1__0");
					put(grammarAccess.getAnnotatedExpressionAccess().getGroup(), "rule__AnnotatedExpression__Group__0");
					put(grammarAccess.getVariableDeclarationAccess().getGroup(), "rule__VariableDeclaration__Group__0");
					put(grammarAccess.getVariableDeclarationAccess().getGroup_5_0(), "rule__VariableDeclaration__Group_5_0__0");
					put(grammarAccess.getVariableDeclarationAccess().getGroup_7(), "rule__VariableDeclaration__Group_7__0");
					put(grammarAccess.getVariableDeclarationWOSemicolonAccess().getGroup_0(), "rule__VariableDeclarationWOSemicolon__Group_0__0");
					put(grammarAccess.getVariableDeclarationWOSemicolonAccess().getGroup_0_5(), "rule__VariableDeclarationWOSemicolon__Group_0_5__0");
					put(grammarAccess.getVariableDeclarationWOSemicolonAccess().getGroup_1(), "rule__VariableDeclarationWOSemicolon__Group_1__0");
					put(grammarAccess.getVariableDeclarationWOSemicolonAccess().getGroup_1_2(), "rule__VariableDeclarationWOSemicolon__Group_1_2__0");
					put(grammarAccess.getReferenceDeclarationAccess().getGroup(), "rule__ReferenceDeclaration__Group__0");
					put(grammarAccess.getReferenceDeclarationAccess().getGroup_4(), "rule__ReferenceDeclaration__Group_4__0");
					put(grammarAccess.getReferenceDeclarationWOSemicolonAccess().getGroup(), "rule__ReferenceDeclarationWOSemicolon__Group__0");
					put(grammarAccess.getReferenceDeclarationWOSemicolonAccess().getGroup_4(), "rule__ReferenceDeclarationWOSemicolon__Group_4__0");
					put(grammarAccess.getValuedObjectAccess().getGroup(), "rule__ValuedObject__Group__0");
					put(grammarAccess.getValuedObjectAccess().getGroup_1(), "rule__ValuedObject__Group_1__0");
					put(grammarAccess.getValuedObjectAccess().getGroup_2(), "rule__ValuedObject__Group_2__0");
					put(grammarAccess.getValuedObjectAccess().getGroup_3(), "rule__ValuedObject__Group_3__0");
					put(grammarAccess.getEmissionAccess().getGroup(), "rule__Emission__Group__0");
					put(grammarAccess.getEmissionAccess().getGroup_2(), "rule__Emission__Group_2__0");
					put(grammarAccess.getAssignmentAccess().getGroup(), "rule__Assignment__Group__0");
					put(grammarAccess.getAssignmentAccess().getGroup_2(), "rule__Assignment__Group_2__0");
					put(grammarAccess.getPostfixEffectAccess().getGroup(), "rule__PostfixEffect__Group__0");
					put(grammarAccess.getPostfixEffectAccess().getGroup_2(), "rule__PostfixEffect__Group_2__0");
					put(grammarAccess.getHostcodeEffectAccess().getGroup(), "rule__HostcodeEffect__Group__0");
					put(grammarAccess.getFunctionCallEffectAccess().getGroup(), "rule__FunctionCallEffect__Group__0");
					put(grammarAccess.getFunctionCallEffectAccess().getGroup_3_0(), "rule__FunctionCallEffect__Group_3_0__0");
					put(grammarAccess.getFunctionCallEffectAccess().getGroup_3_0_2(), "rule__FunctionCallEffect__Group_3_0_2__0");
					put(grammarAccess.getLogicalOrExpressionAccess().getGroup(), "rule__LogicalOrExpression__Group__0");
					put(grammarAccess.getLogicalOrExpressionAccess().getGroup_1(), "rule__LogicalOrExpression__Group_1__0");
					put(grammarAccess.getLogicalOrExpressionAccess().getGroup_1_1(), "rule__LogicalOrExpression__Group_1_1__0");
					put(grammarAccess.getLogicalAndExpressionAccess().getGroup(), "rule__LogicalAndExpression__Group__0");
					put(grammarAccess.getLogicalAndExpressionAccess().getGroup_1(), "rule__LogicalAndExpression__Group_1__0");
					put(grammarAccess.getLogicalAndExpressionAccess().getGroup_1_1(), "rule__LogicalAndExpression__Group_1_1__0");
					put(grammarAccess.getBitwiseOrExpressionAccess().getGroup(), "rule__BitwiseOrExpression__Group__0");
					put(grammarAccess.getBitwiseOrExpressionAccess().getGroup_1(), "rule__BitwiseOrExpression__Group_1__0");
					put(grammarAccess.getBitwiseOrExpressionAccess().getGroup_1_1(), "rule__BitwiseOrExpression__Group_1_1__0");
					put(grammarAccess.getBitwiseAndExpressionAccess().getGroup(), "rule__BitwiseAndExpression__Group__0");
					put(grammarAccess.getBitwiseAndExpressionAccess().getGroup_1(), "rule__BitwiseAndExpression__Group_1__0");
					put(grammarAccess.getBitwiseAndExpressionAccess().getGroup_1_1(), "rule__BitwiseAndExpression__Group_1_1__0");
					put(grammarAccess.getCompareOperationAccess().getGroup(), "rule__CompareOperation__Group__0");
					put(grammarAccess.getCompareOperationAccess().getGroup_1(), "rule__CompareOperation__Group_1__0");
					put(grammarAccess.getNotExpressionAccess().getGroup_0(), "rule__NotExpression__Group_0__0");
					put(grammarAccess.getAddExpressionAccess().getGroup(), "rule__AddExpression__Group__0");
					put(grammarAccess.getAddExpressionAccess().getGroup_1(), "rule__AddExpression__Group_1__0");
					put(grammarAccess.getAddExpressionAccess().getGroup_1_1(), "rule__AddExpression__Group_1_1__0");
					put(grammarAccess.getSubExpressionAccess().getGroup(), "rule__SubExpression__Group__0");
					put(grammarAccess.getSubExpressionAccess().getGroup_1(), "rule__SubExpression__Group_1__0");
					put(grammarAccess.getSubExpressionAccess().getGroup_1_1(), "rule__SubExpression__Group_1_1__0");
					put(grammarAccess.getMultExpressionAccess().getGroup(), "rule__MultExpression__Group__0");
					put(grammarAccess.getMultExpressionAccess().getGroup_1(), "rule__MultExpression__Group_1__0");
					put(grammarAccess.getMultExpressionAccess().getGroup_1_1(), "rule__MultExpression__Group_1_1__0");
					put(grammarAccess.getDivExpressionAccess().getGroup(), "rule__DivExpression__Group__0");
					put(grammarAccess.getDivExpressionAccess().getGroup_1(), "rule__DivExpression__Group_1__0");
					put(grammarAccess.getDivExpressionAccess().getGroup_1_1(), "rule__DivExpression__Group_1_1__0");
					put(grammarAccess.getModExpressionAccess().getGroup(), "rule__ModExpression__Group__0");
					put(grammarAccess.getModExpressionAccess().getGroup_1(), "rule__ModExpression__Group_1__0");
					put(grammarAccess.getModExpressionAccess().getGroup_1_1(), "rule__ModExpression__Group_1_1__0");
					put(grammarAccess.getNegExpressionAccess().getGroup_0(), "rule__NegExpression__Group_0__0");
					put(grammarAccess.getAtomicValuedExpressionAccess().getGroup_3(), "rule__AtomicValuedExpression__Group_3__0");
					put(grammarAccess.getValuedObjectTestExpressionAccess().getGroup_0(), "rule__ValuedObjectTestExpression__Group_0__0");
					put(grammarAccess.getValuedObjectReferenceAccess().getGroup(), "rule__ValuedObjectReference__Group__0");
					put(grammarAccess.getValuedObjectReferenceAccess().getGroup_1(), "rule__ValuedObjectReference__Group_1__0");
					put(grammarAccess.getValuedObjectReferenceAccess().getGroup_2(), "rule__ValuedObjectReference__Group_2__0");
					put(grammarAccess.getFunctionCallAccess().getGroup(), "rule__FunctionCall__Group__0");
					put(grammarAccess.getFunctionCallAccess().getGroup_2_0(), "rule__FunctionCall__Group_2_0__0");
					put(grammarAccess.getFunctionCallAccess().getGroup_2_0_2(), "rule__FunctionCall__Group_2_0_2__0");
					put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
					put(grammarAccess.getParameterAccess().getGroup_0(), "rule__Parameter__Group_0__0");
					put(grammarAccess.getTagAnnotationAccess().getGroup(), "rule__TagAnnotation__Group__0");
					put(grammarAccess.getKeyStringValueAnnotationAccess().getGroup(), "rule__KeyStringValueAnnotation__Group__0");
					put(grammarAccess.getKeyStringValueAnnotationAccess().getGroup_3(), "rule__KeyStringValueAnnotation__Group_3__0");
					put(grammarAccess.getRestrictedKeyStringValueAnnotationAccess().getGroup(), "rule__RestrictedKeyStringValueAnnotation__Group__0");
					put(grammarAccess.getRestrictedKeyStringValueAnnotationAccess().getGroup_3(), "rule__RestrictedKeyStringValueAnnotation__Group_3__0");
					put(grammarAccess.getTypedKeyStringValueAnnotationAccess().getGroup(), "rule__TypedKeyStringValueAnnotation__Group__0");
					put(grammarAccess.getTypedKeyStringValueAnnotationAccess().getGroup_6(), "rule__TypedKeyStringValueAnnotation__Group_6__0");
					put(grammarAccess.getRestrictedTypedKeyStringValueAnnotationAccess().getGroup(), "rule__RestrictedTypedKeyStringValueAnnotation__Group__0");
					put(grammarAccess.getRestrictedTypedKeyStringValueAnnotationAccess().getGroup_6(), "rule__RestrictedTypedKeyStringValueAnnotation__Group_6__0");
					put(grammarAccess.getQuotedKeyStringValueAnnotationAccess().getGroup(), "rule__QuotedKeyStringValueAnnotation__Group__0");
					put(grammarAccess.getQuotedKeyStringValueAnnotationAccess().getGroup_3(), "rule__QuotedKeyStringValueAnnotation__Group_3__0");
					put(grammarAccess.getQuotedTypedKeyStringValueAnnotationAccess().getGroup(), "rule__QuotedTypedKeyStringValueAnnotation__Group__0");
					put(grammarAccess.getQuotedTypedKeyStringValueAnnotationAccess().getGroup_6(), "rule__QuotedTypedKeyStringValueAnnotation__Group_6__0");
					put(grammarAccess.getExtendedIDAccess().getGroup(), "rule__ExtendedID__Group__0");
					put(grammarAccess.getExtendedIDAccess().getGroup_1(), "rule__ExtendedID__Group_1__0");
					put(grammarAccess.getExtendedIDAccess().getGroup_2(), "rule__ExtendedID__Group_2__0");
					put(grammarAccess.getIntegerAccess().getGroup(), "rule__Integer__Group__0");
					put(grammarAccess.getFloategerAccess().getGroup(), "rule__Floateger__Group__0");
					put(grammarAccess.getSCChartsAccess().getRootStatesAssignment(), "rule__SCCharts__RootStatesAssignment");
					put(grammarAccess.getRootStateAccess().getAnnotationsAssignment_0(), "rule__RootState__AnnotationsAssignment_0");
					put(grammarAccess.getRootStateAccess().getIdAssignment_2(), "rule__RootState__IdAssignment_2");
					put(grammarAccess.getRootStateAccess().getLabelAssignment_3(), "rule__RootState__LabelAssignment_3");
					put(grammarAccess.getRootStateAccess().getDeclarationsAssignment_5(), "rule__RootState__DeclarationsAssignment_5");
					put(grammarAccess.getRootStateAccess().getLocalActionsAssignment_6(), "rule__RootState__LocalActionsAssignment_6");
					put(grammarAccess.getRootStateAccess().getRegionsAssignment_7_0(), "rule__RootState__RegionsAssignment_7_0");
					put(grammarAccess.getRootStateAccess().getRegionsAssignment_7_1(), "rule__RootState__RegionsAssignment_7_1");
					put(grammarAccess.getRootStateAccess().getRegionsAssignment_7_2(), "rule__RootState__RegionsAssignment_7_2");
					put(grammarAccess.getStateAccess().getAnnotationsAssignment_0(), "rule__State__AnnotationsAssignment_0");
					put(grammarAccess.getStateAccess().getInitialAssignment_1(), "rule__State__InitialAssignment_1");
					put(grammarAccess.getStateAccess().getFinalAssignment_2(), "rule__State__FinalAssignment_2");
					put(grammarAccess.getStateAccess().getConnectorAssignment_3(), "rule__State__ConnectorAssignment_3");
					put(grammarAccess.getStateAccess().getIdAssignment_5(), "rule__State__IdAssignment_5");
					put(grammarAccess.getStateAccess().getLabelAssignment_6(), "rule__State__LabelAssignment_6");
					put(grammarAccess.getStateAccess().getDeclarationsAssignment_7_1(), "rule__State__DeclarationsAssignment_7_1");
					put(grammarAccess.getStateAccess().getLocalActionsAssignment_7_2(), "rule__State__LocalActionsAssignment_7_2");
					put(grammarAccess.getStateAccess().getRegionsAssignment_7_3_0(), "rule__State__RegionsAssignment_7_3_0");
					put(grammarAccess.getStateAccess().getRegionsAssignment_7_3_1(), "rule__State__RegionsAssignment_7_3_1");
					put(grammarAccess.getStateAccess().getRegionsAssignment_7_3_2(), "rule__State__RegionsAssignment_7_3_2");
					put(grammarAccess.getStateAccess().getOutgoingTransitionsAssignment_8(), "rule__State__OutgoingTransitionsAssignment_8");
					put(grammarAccess.getTransitionAccess().getAnnotationsAssignment_0(), "rule__Transition__AnnotationsAssignment_0");
					put(grammarAccess.getTransitionAccess().getTypeAssignment_1(), "rule__Transition__TypeAssignment_1");
					put(grammarAccess.getTransitionAccess().getTargetStateAssignment_2(), "rule__Transition__TargetStateAssignment_2");
					put(grammarAccess.getTransitionAccess().getImmediateAssignment_3(), "rule__Transition__ImmediateAssignment_3");
					put(grammarAccess.getTransitionAccess().getDeferredAssignment_4(), "rule__Transition__DeferredAssignment_4");
					put(grammarAccess.getTransitionAccess().getHistoryAssignment_5(), "rule__Transition__HistoryAssignment_5");
					put(grammarAccess.getTransitionAccess().getDelayAssignment_6_0_0_1(), "rule__Transition__DelayAssignment_6_0_0_1");
					put(grammarAccess.getTransitionAccess().getTriggerAssignment_6_0_0_2(), "rule__Transition__TriggerAssignment_6_0_0_2");
					put(grammarAccess.getTransitionAccess().getEffectsAssignment_6_0_1_1(), "rule__Transition__EffectsAssignment_6_0_1_1");
					put(grammarAccess.getTransitionAccess().getEffectsAssignment_6_0_1_2_1(), "rule__Transition__EffectsAssignment_6_0_1_2_1");
					put(grammarAccess.getTransitionAccess().getLabelAssignment_6_1_1(), "rule__Transition__LabelAssignment_6_1_1");
					put(grammarAccess.getEntryActionAccess().getTriggerAssignment_2_1(), "rule__EntryAction__TriggerAssignment_2_1");
					put(grammarAccess.getEntryActionAccess().getEffectsAssignment_3_1(), "rule__EntryAction__EffectsAssignment_3_1");
					put(grammarAccess.getEntryActionAccess().getEffectsAssignment_3_2_1(), "rule__EntryAction__EffectsAssignment_3_2_1");
					put(grammarAccess.getDuringActionAccess().getImmediateAssignment_1(), "rule__DuringAction__ImmediateAssignment_1");
					put(grammarAccess.getDuringActionAccess().getTriggerAssignment_3_1(), "rule__DuringAction__TriggerAssignment_3_1");
					put(grammarAccess.getDuringActionAccess().getEffectsAssignment_4_1(), "rule__DuringAction__EffectsAssignment_4_1");
					put(grammarAccess.getDuringActionAccess().getEffectsAssignment_4_2_1(), "rule__DuringAction__EffectsAssignment_4_2_1");
					put(grammarAccess.getExitActionAccess().getTriggerAssignment_2_1(), "rule__ExitAction__TriggerAssignment_2_1");
					put(grammarAccess.getExitActionAccess().getEffectsAssignment_3_1(), "rule__ExitAction__EffectsAssignment_3_1");
					put(grammarAccess.getExitActionAccess().getEffectsAssignment_3_2_1(), "rule__ExitAction__EffectsAssignment_3_2_1");
					put(grammarAccess.getSuspendActionAccess().getImmediateAssignment_1(), "rule__SuspendAction__ImmediateAssignment_1");
					put(grammarAccess.getSuspendActionAccess().getWeakAssignment_2(), "rule__SuspendAction__WeakAssignment_2");
					put(grammarAccess.getSuspendActionAccess().getTriggerAssignment_4_1(), "rule__SuspendAction__TriggerAssignment_4_1");
					put(grammarAccess.getIterateActionAccess().getImmediateAssignment_1(), "rule__IterateAction__ImmediateAssignment_1");
					put(grammarAccess.getIterateActionAccess().getTriggerAssignment_3_1(), "rule__IterateAction__TriggerAssignment_3_1");
					put(grammarAccess.getIterateActionAccess().getEffectsAssignment_4_1(), "rule__IterateAction__EffectsAssignment_4_1");
					put(grammarAccess.getIterateActionAccess().getEffectsAssignment_4_2_1(), "rule__IterateAction__EffectsAssignment_4_2_1");
					put(grammarAccess.getInitActionAccess().getTriggerAssignment_2_1(), "rule__InitAction__TriggerAssignment_2_1");
					put(grammarAccess.getInitActionAccess().getEffectsAssignment_3_1(), "rule__InitAction__EffectsAssignment_3_1");
					put(grammarAccess.getInitActionAccess().getEffectsAssignment_3_2_1(), "rule__InitAction__EffectsAssignment_3_2_1");
					put(grammarAccess.getFinalActionAccess().getTriggerAssignment_2_1(), "rule__FinalAction__TriggerAssignment_2_1");
					put(grammarAccess.getFinalActionAccess().getEffectsAssignment_3_1(), "rule__FinalAction__EffectsAssignment_3_1");
					put(grammarAccess.getFinalActionAccess().getEffectsAssignment_3_2_1(), "rule__FinalAction__EffectsAssignment_3_2_1");
					put(grammarAccess.getSingleControlflowRegionAccess().getStatesAssignment_1(), "rule__SingleControlflowRegion__StatesAssignment_1");
					put(grammarAccess.getSingleDataflowRegionAccess().getEquationsAssignment_1(), "rule__SingleDataflowRegion__EquationsAssignment_1");
					put(grammarAccess.getControlflowRegionAccess().getAnnotationsAssignment_1(), "rule__ControlflowRegion__AnnotationsAssignment_1");
					put(grammarAccess.getControlflowRegionAccess().getIdAssignment_3(), "rule__ControlflowRegion__IdAssignment_3");
					put(grammarAccess.getControlflowRegionAccess().getLabelAssignment_4(), "rule__ControlflowRegion__LabelAssignment_4");
					put(grammarAccess.getControlflowRegionAccess().getDeclarationsAssignment_6(), "rule__ControlflowRegion__DeclarationsAssignment_6");
					put(grammarAccess.getControlflowRegionAccess().getStatesAssignment_7(), "rule__ControlflowRegion__StatesAssignment_7");
					put(grammarAccess.getDataflowRegionAccess().getAnnotationsAssignment_1(), "rule__DataflowRegion__AnnotationsAssignment_1");
					put(grammarAccess.getDataflowRegionAccess().getIdAssignment_3(), "rule__DataflowRegion__IdAssignment_3");
					put(grammarAccess.getDataflowRegionAccess().getLabelAssignment_4(), "rule__DataflowRegion__LabelAssignment_4");
					put(grammarAccess.getDataflowRegionAccess().getDeclarationsAssignment_6(), "rule__DataflowRegion__DeclarationsAssignment_6");
					put(grammarAccess.getDataflowRegionAccess().getEquationsAssignment_7(), "rule__DataflowRegion__EquationsAssignment_7");
					put(grammarAccess.getDFAssignmentAccess().getAnnotationsAssignment_0(), "rule__DFAssignment__AnnotationsAssignment_0");
					put(grammarAccess.getDFAssignmentAccess().getValuedObjectAssignment_1(), "rule__DFAssignment__ValuedObjectAssignment_1");
					put(grammarAccess.getDFAssignmentAccess().getIndicesAssignment_2_1(), "rule__DFAssignment__IndicesAssignment_2_1");
					put(grammarAccess.getDFAssignmentAccess().getOperatorAssignment_3(), "rule__DFAssignment__OperatorAssignment_3");
					put(grammarAccess.getDFAssignmentAccess().getExpressionAssignment_4(), "rule__DFAssignment__ExpressionAssignment_4");
					put(grammarAccess.getEquationAccess().getValuedObjectAssignment_1_0(), "rule__Equation__ValuedObjectAssignment_1_0");
					put(grammarAccess.getEquationAccess().getExpressionAssignment_1_2(), "rule__Equation__ExpressionAssignment_1_2");
					put(grammarAccess.getBindingAccess().getAnnotationsAssignment_0(), "rule__Binding__AnnotationsAssignment_0");
					put(grammarAccess.getBindingAccess().getFormalAssignment_1(), "rule__Binding__FormalAssignment_1");
					put(grammarAccess.getBindingAccess().getActualAssignment_3(), "rule__Binding__ActualAssignment_3");
					put(grammarAccess.getKextAccess().getScopesAssignment(), "rule__Kext__ScopesAssignment");
					put(grammarAccess.getScopeAccess().getIdAssignment_1_1(), "rule__Scope__IdAssignment_1_1");
					put(grammarAccess.getScopeAccess().getDeclarationsAssignment_2(), "rule__Scope__DeclarationsAssignment_2");
					put(grammarAccess.getScopeAccess().getEntitiesAssignment_3(), "rule__Scope__EntitiesAssignment_3");
					put(grammarAccess.getTestEntityAccess().getExpressionAssignment_0(), "rule__TestEntity__ExpressionAssignment_0");
					put(grammarAccess.getTestEntityAccess().getEffectAssignment_1(), "rule__TestEntity__EffectAssignment_1");
					put(grammarAccess.getAnnotatedExpressionAccess().getAnnotationsAssignment_0(), "rule__AnnotatedExpression__AnnotationsAssignment_0");
					put(grammarAccess.getAnnotatedExpressionAccess().getExpressionAssignment_2(), "rule__AnnotatedExpression__ExpressionAssignment_2");
					put(grammarAccess.getVariableDeclarationAccess().getAnnotationsAssignment_0(), "rule__VariableDeclaration__AnnotationsAssignment_0");
					put(grammarAccess.getVariableDeclarationAccess().getConstAssignment_1(), "rule__VariableDeclaration__ConstAssignment_1");
					put(grammarAccess.getVariableDeclarationAccess().getInputAssignment_2(), "rule__VariableDeclaration__InputAssignment_2");
					put(grammarAccess.getVariableDeclarationAccess().getOutputAssignment_3(), "rule__VariableDeclaration__OutputAssignment_3");
					put(grammarAccess.getVariableDeclarationAccess().getStaticAssignment_4(), "rule__VariableDeclaration__StaticAssignment_4");
					put(grammarAccess.getVariableDeclarationAccess().getSignalAssignment_5_0_0(), "rule__VariableDeclaration__SignalAssignment_5_0_0");
					put(grammarAccess.getVariableDeclarationAccess().getTypeAssignment_5_0_1(), "rule__VariableDeclaration__TypeAssignment_5_0_1");
					put(grammarAccess.getVariableDeclarationAccess().getSignalAssignment_5_1(), "rule__VariableDeclaration__SignalAssignment_5_1");
					put(grammarAccess.getVariableDeclarationAccess().getValuedObjectsAssignment_6(), "rule__VariableDeclaration__ValuedObjectsAssignment_6");
					put(grammarAccess.getVariableDeclarationAccess().getValuedObjectsAssignment_7_1(), "rule__VariableDeclaration__ValuedObjectsAssignment_7_1");
					put(grammarAccess.getVariableDeclarationWOSemicolonAccess().getAnnotationsAssignment_0_0(), "rule__VariableDeclarationWOSemicolon__AnnotationsAssignment_0_0");
					put(grammarAccess.getVariableDeclarationWOSemicolonAccess().getConstAssignment_0_1(), "rule__VariableDeclarationWOSemicolon__ConstAssignment_0_1");
					put(grammarAccess.getVariableDeclarationWOSemicolonAccess().getInputAssignment_0_2(), "rule__VariableDeclarationWOSemicolon__InputAssignment_0_2");
					put(grammarAccess.getVariableDeclarationWOSemicolonAccess().getOutputAssignment_0_3(), "rule__VariableDeclarationWOSemicolon__OutputAssignment_0_3");
					put(grammarAccess.getVariableDeclarationWOSemicolonAccess().getStaticAssignment_0_4(), "rule__VariableDeclarationWOSemicolon__StaticAssignment_0_4");
					put(grammarAccess.getVariableDeclarationWOSemicolonAccess().getSignalAssignment_0_5_0(), "rule__VariableDeclarationWOSemicolon__SignalAssignment_0_5_0");
					put(grammarAccess.getVariableDeclarationWOSemicolonAccess().getTypeAssignment_0_5_1(), "rule__VariableDeclarationWOSemicolon__TypeAssignment_0_5_1");
					put(grammarAccess.getVariableDeclarationWOSemicolonAccess().getSignalAssignment_1_0(), "rule__VariableDeclarationWOSemicolon__SignalAssignment_1_0");
					put(grammarAccess.getVariableDeclarationWOSemicolonAccess().getValuedObjectsAssignment_1_1(), "rule__VariableDeclarationWOSemicolon__ValuedObjectsAssignment_1_1");
					put(grammarAccess.getVariableDeclarationWOSemicolonAccess().getValuedObjectsAssignment_1_2_1(), "rule__VariableDeclarationWOSemicolon__ValuedObjectsAssignment_1_2_1");
					put(grammarAccess.getReferenceDeclarationAccess().getAnnotationsAssignment_0(), "rule__ReferenceDeclaration__AnnotationsAssignment_0");
					put(grammarAccess.getReferenceDeclarationAccess().getReferenceAssignment_2(), "rule__ReferenceDeclaration__ReferenceAssignment_2");
					put(grammarAccess.getReferenceDeclarationAccess().getValuedObjectsAssignment_3(), "rule__ReferenceDeclaration__ValuedObjectsAssignment_3");
					put(grammarAccess.getReferenceDeclarationAccess().getValuedObjectsAssignment_4_1(), "rule__ReferenceDeclaration__ValuedObjectsAssignment_4_1");
					put(grammarAccess.getReferenceDeclarationWOSemicolonAccess().getAnnotationsAssignment_0(), "rule__ReferenceDeclarationWOSemicolon__AnnotationsAssignment_0");
					put(grammarAccess.getReferenceDeclarationWOSemicolonAccess().getReferenceAssignment_2(), "rule__ReferenceDeclarationWOSemicolon__ReferenceAssignment_2");
					put(grammarAccess.getReferenceDeclarationWOSemicolonAccess().getValuedObjectsAssignment_3(), "rule__ReferenceDeclarationWOSemicolon__ValuedObjectsAssignment_3");
					put(grammarAccess.getReferenceDeclarationWOSemicolonAccess().getValuedObjectsAssignment_4_1(), "rule__ReferenceDeclarationWOSemicolon__ValuedObjectsAssignment_4_1");
					put(grammarAccess.getValuedObjectAccess().getNameAssignment_0(), "rule__ValuedObject__NameAssignment_0");
					put(grammarAccess.getValuedObjectAccess().getCardinalitiesAssignment_1_1(), "rule__ValuedObject__CardinalitiesAssignment_1_1");
					put(grammarAccess.getValuedObjectAccess().getInitialValueAssignment_2_1(), "rule__ValuedObject__InitialValueAssignment_2_1");
					put(grammarAccess.getValuedObjectAccess().getCombineOperatorAssignment_3_1(), "rule__ValuedObject__CombineOperatorAssignment_3_1");
					put(grammarAccess.getEmissionAccess().getAnnotationsAssignment_0(), "rule__Emission__AnnotationsAssignment_0");
					put(grammarAccess.getEmissionAccess().getValuedObjectAssignment_1(), "rule__Emission__ValuedObjectAssignment_1");
					put(grammarAccess.getEmissionAccess().getNewValueAssignment_2_1(), "rule__Emission__NewValueAssignment_2_1");
					put(grammarAccess.getAssignmentAccess().getAnnotationsAssignment_0(), "rule__Assignment__AnnotationsAssignment_0");
					put(grammarAccess.getAssignmentAccess().getValuedObjectAssignment_1(), "rule__Assignment__ValuedObjectAssignment_1");
					put(grammarAccess.getAssignmentAccess().getIndicesAssignment_2_1(), "rule__Assignment__IndicesAssignment_2_1");
					put(grammarAccess.getAssignmentAccess().getOperatorAssignment_3(), "rule__Assignment__OperatorAssignment_3");
					put(grammarAccess.getAssignmentAccess().getExpressionAssignment_4(), "rule__Assignment__ExpressionAssignment_4");
					put(grammarAccess.getPostfixEffectAccess().getAnnotationsAssignment_0(), "rule__PostfixEffect__AnnotationsAssignment_0");
					put(grammarAccess.getPostfixEffectAccess().getValuedObjectAssignment_1(), "rule__PostfixEffect__ValuedObjectAssignment_1");
					put(grammarAccess.getPostfixEffectAccess().getIndicesAssignment_2_1(), "rule__PostfixEffect__IndicesAssignment_2_1");
					put(grammarAccess.getPostfixEffectAccess().getOperatorAssignment_3(), "rule__PostfixEffect__OperatorAssignment_3");
					put(grammarAccess.getHostcodeEffectAccess().getAnnotationsAssignment_0(), "rule__HostcodeEffect__AnnotationsAssignment_0");
					put(grammarAccess.getHostcodeEffectAccess().getTextAssignment_1(), "rule__HostcodeEffect__TextAssignment_1");
					put(grammarAccess.getFunctionCallEffectAccess().getAnnotationsAssignment_0(), "rule__FunctionCallEffect__AnnotationsAssignment_0");
					put(grammarAccess.getFunctionCallEffectAccess().getFunctionNameAssignment_2(), "rule__FunctionCallEffect__FunctionNameAssignment_2");
					put(grammarAccess.getFunctionCallEffectAccess().getParametersAssignment_3_0_1(), "rule__FunctionCallEffect__ParametersAssignment_3_0_1");
					put(grammarAccess.getFunctionCallEffectAccess().getParametersAssignment_3_0_2_1(), "rule__FunctionCallEffect__ParametersAssignment_3_0_2_1");
					put(grammarAccess.getLogicalOrExpressionAccess().getOperatorAssignment_1_1_0(), "rule__LogicalOrExpression__OperatorAssignment_1_1_0");
					put(grammarAccess.getLogicalOrExpressionAccess().getSubExpressionsAssignment_1_1_1(), "rule__LogicalOrExpression__SubExpressionsAssignment_1_1_1");
					put(grammarAccess.getLogicalAndExpressionAccess().getOperatorAssignment_1_1_0(), "rule__LogicalAndExpression__OperatorAssignment_1_1_0");
					put(grammarAccess.getLogicalAndExpressionAccess().getSubExpressionsAssignment_1_1_1(), "rule__LogicalAndExpression__SubExpressionsAssignment_1_1_1");
					put(grammarAccess.getBitwiseOrExpressionAccess().getOperatorAssignment_1_1_0(), "rule__BitwiseOrExpression__OperatorAssignment_1_1_0");
					put(grammarAccess.getBitwiseOrExpressionAccess().getSubExpressionsAssignment_1_1_1(), "rule__BitwiseOrExpression__SubExpressionsAssignment_1_1_1");
					put(grammarAccess.getBitwiseAndExpressionAccess().getOperatorAssignment_1_1_0(), "rule__BitwiseAndExpression__OperatorAssignment_1_1_0");
					put(grammarAccess.getBitwiseAndExpressionAccess().getSubExpressionsAssignment_1_1_1(), "rule__BitwiseAndExpression__SubExpressionsAssignment_1_1_1");
					put(grammarAccess.getCompareOperationAccess().getOperatorAssignment_1_1(), "rule__CompareOperation__OperatorAssignment_1_1");
					put(grammarAccess.getCompareOperationAccess().getSubExpressionsAssignment_1_2(), "rule__CompareOperation__SubExpressionsAssignment_1_2");
					put(grammarAccess.getNotExpressionAccess().getOperatorAssignment_0_1(), "rule__NotExpression__OperatorAssignment_0_1");
					put(grammarAccess.getNotExpressionAccess().getSubExpressionsAssignment_0_2(), "rule__NotExpression__SubExpressionsAssignment_0_2");
					put(grammarAccess.getAddExpressionAccess().getOperatorAssignment_1_1_0(), "rule__AddExpression__OperatorAssignment_1_1_0");
					put(grammarAccess.getAddExpressionAccess().getSubExpressionsAssignment_1_1_1(), "rule__AddExpression__SubExpressionsAssignment_1_1_1");
					put(grammarAccess.getSubExpressionAccess().getOperatorAssignment_1_1_0(), "rule__SubExpression__OperatorAssignment_1_1_0");
					put(grammarAccess.getSubExpressionAccess().getSubExpressionsAssignment_1_1_1(), "rule__SubExpression__SubExpressionsAssignment_1_1_1");
					put(grammarAccess.getMultExpressionAccess().getOperatorAssignment_1_1_0(), "rule__MultExpression__OperatorAssignment_1_1_0");
					put(grammarAccess.getMultExpressionAccess().getSubExpressionsAssignment_1_1_1(), "rule__MultExpression__SubExpressionsAssignment_1_1_1");
					put(grammarAccess.getDivExpressionAccess().getOperatorAssignment_1_1_0(), "rule__DivExpression__OperatorAssignment_1_1_0");
					put(grammarAccess.getDivExpressionAccess().getSubExpressionsAssignment_1_1_1(), "rule__DivExpression__SubExpressionsAssignment_1_1_1");
					put(grammarAccess.getModExpressionAccess().getOperatorAssignment_1_1_0(), "rule__ModExpression__OperatorAssignment_1_1_0");
					put(grammarAccess.getModExpressionAccess().getSubExpressionsAssignment_1_1_1(), "rule__ModExpression__SubExpressionsAssignment_1_1_1");
					put(grammarAccess.getNegExpressionAccess().getOperatorAssignment_0_1(), "rule__NegExpression__OperatorAssignment_0_1");
					put(grammarAccess.getNegExpressionAccess().getSubExpressionsAssignment_0_2(), "rule__NegExpression__SubExpressionsAssignment_0_2");
					put(grammarAccess.getValuedObjectTestExpressionAccess().getOperatorAssignment_0_1(), "rule__ValuedObjectTestExpression__OperatorAssignment_0_1");
					put(grammarAccess.getValuedObjectTestExpressionAccess().getSubExpressionsAssignment_0_3(), "rule__ValuedObjectTestExpression__SubExpressionsAssignment_0_3");
					put(grammarAccess.getValuedObjectReferenceAccess().getValuedObjectAssignment_0(), "rule__ValuedObjectReference__ValuedObjectAssignment_0");
					put(grammarAccess.getValuedObjectReferenceAccess().getSubReferenceAssignment_1_1(), "rule__ValuedObjectReference__SubReferenceAssignment_1_1");
					put(grammarAccess.getValuedObjectReferenceAccess().getIndicesAssignment_2_1(), "rule__ValuedObjectReference__IndicesAssignment_2_1");
					put(grammarAccess.getFunctionCallAccess().getFunctionNameAssignment_1(), "rule__FunctionCall__FunctionNameAssignment_1");
					put(grammarAccess.getFunctionCallAccess().getParametersAssignment_2_0_1(), "rule__FunctionCall__ParametersAssignment_2_0_1");
					put(grammarAccess.getFunctionCallAccess().getParametersAssignment_2_0_2_1(), "rule__FunctionCall__ParametersAssignment_2_0_2_1");
					put(grammarAccess.getParameterAccess().getPureOutputAssignment_0_0(), "rule__Parameter__PureOutputAssignment_0_0");
					put(grammarAccess.getParameterAccess().getCallByReferenceAssignment_0_1(), "rule__Parameter__CallByReferenceAssignment_0_1");
					put(grammarAccess.getParameterAccess().getExpressionAssignment_1(), "rule__Parameter__ExpressionAssignment_1");
					put(grammarAccess.getTextExpressionAccess().getTextAssignment(), "rule__TextExpression__TextAssignment");
					put(grammarAccess.getIntValueAccess().getValueAssignment(), "rule__IntValue__ValueAssignment");
					put(grammarAccess.getFloatValueAccess().getValueAssignment(), "rule__FloatValue__ValueAssignment");
					put(grammarAccess.getBoolValueAccess().getValueAssignment(), "rule__BoolValue__ValueAssignment");
					put(grammarAccess.getStringValueAccess().getValueAssignment(), "rule__StringValue__ValueAssignment");
					put(grammarAccess.getCommentAnnotationAccess().getValuesAssignment(), "rule__CommentAnnotation__ValuesAssignment");
					put(grammarAccess.getTagAnnotationAccess().getNameAssignment_1(), "rule__TagAnnotation__NameAssignment_1");
					put(grammarAccess.getKeyStringValueAnnotationAccess().getNameAssignment_1(), "rule__KeyStringValueAnnotation__NameAssignment_1");
					put(grammarAccess.getKeyStringValueAnnotationAccess().getValuesAssignment_2(), "rule__KeyStringValueAnnotation__ValuesAssignment_2");
					put(grammarAccess.getKeyStringValueAnnotationAccess().getValuesAssignment_3_1(), "rule__KeyStringValueAnnotation__ValuesAssignment_3_1");
					put(grammarAccess.getRestrictedKeyStringValueAnnotationAccess().getNameAssignment_1(), "rule__RestrictedKeyStringValueAnnotation__NameAssignment_1");
					put(grammarAccess.getRestrictedKeyStringValueAnnotationAccess().getValuesAssignment_2(), "rule__RestrictedKeyStringValueAnnotation__ValuesAssignment_2");
					put(grammarAccess.getRestrictedKeyStringValueAnnotationAccess().getValuesAssignment_3_1(), "rule__RestrictedKeyStringValueAnnotation__ValuesAssignment_3_1");
					put(grammarAccess.getTypedKeyStringValueAnnotationAccess().getNameAssignment_1(), "rule__TypedKeyStringValueAnnotation__NameAssignment_1");
					put(grammarAccess.getTypedKeyStringValueAnnotationAccess().getTypeAssignment_3(), "rule__TypedKeyStringValueAnnotation__TypeAssignment_3");
					put(grammarAccess.getTypedKeyStringValueAnnotationAccess().getValuesAssignment_5(), "rule__TypedKeyStringValueAnnotation__ValuesAssignment_5");
					put(grammarAccess.getTypedKeyStringValueAnnotationAccess().getValuesAssignment_6_1(), "rule__TypedKeyStringValueAnnotation__ValuesAssignment_6_1");
					put(grammarAccess.getRestrictedTypedKeyStringValueAnnotationAccess().getNameAssignment_1(), "rule__RestrictedTypedKeyStringValueAnnotation__NameAssignment_1");
					put(grammarAccess.getRestrictedTypedKeyStringValueAnnotationAccess().getTypeAssignment_3(), "rule__RestrictedTypedKeyStringValueAnnotation__TypeAssignment_3");
					put(grammarAccess.getRestrictedTypedKeyStringValueAnnotationAccess().getValuesAssignment_5(), "rule__RestrictedTypedKeyStringValueAnnotation__ValuesAssignment_5");
					put(grammarAccess.getRestrictedTypedKeyStringValueAnnotationAccess().getValuesAssignment_6_1(), "rule__RestrictedTypedKeyStringValueAnnotation__ValuesAssignment_6_1");
					put(grammarAccess.getQuotedKeyStringValueAnnotationAccess().getNameAssignment_1(), "rule__QuotedKeyStringValueAnnotation__NameAssignment_1");
					put(grammarAccess.getQuotedKeyStringValueAnnotationAccess().getValuesAssignment_2(), "rule__QuotedKeyStringValueAnnotation__ValuesAssignment_2");
					put(grammarAccess.getQuotedKeyStringValueAnnotationAccess().getValuesAssignment_3_1(), "rule__QuotedKeyStringValueAnnotation__ValuesAssignment_3_1");
					put(grammarAccess.getQuotedTypedKeyStringValueAnnotationAccess().getNameAssignment_1(), "rule__QuotedTypedKeyStringValueAnnotation__NameAssignment_1");
					put(grammarAccess.getQuotedTypedKeyStringValueAnnotationAccess().getTypeAssignment_3(), "rule__QuotedTypedKeyStringValueAnnotation__TypeAssignment_3");
					put(grammarAccess.getQuotedTypedKeyStringValueAnnotationAccess().getValuesAssignment_5(), "rule__QuotedTypedKeyStringValueAnnotation__ValuesAssignment_5");
					put(grammarAccess.getQuotedTypedKeyStringValueAnnotationAccess().getValuesAssignment_6_1(), "rule__QuotedTypedKeyStringValueAnnotation__ValuesAssignment_6_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			de.cau.cs.kieler.sccharts.text3.ui.contentassist.antlr.internal.InternalSct3Parser typedParser = (de.cau.cs.kieler.sccharts.text3.ui.contentassist.antlr.internal.InternalSct3Parser) parser;
			typedParser.entryRuleSCCharts();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public Sct3GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(Sct3GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
