/*
 * generated by Xtext
 */
package de.cau.cs.kieler.kicool.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.cau.cs.kieler.kicool.ui.internal.KiCoolActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class KiCoolExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return KiCoolActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return KiCoolActivator.getInstance().getInjector(KiCoolActivator.DE_CAU_CS_KIELER_KICOOL_KICOOL);
	}
	
}
