/*
 * generated by Xtext
 */
package de.cau.cs.kieler.esterel.ui.scest.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class SCEstProposalProvider extends AbstractSCEstProposalProvider {
}
