grammar de.cau.cs.kieler.yakindu.sccharts.model.stext.SCChartsExp
with de.cau.cs.kieler.yakindu.model.stext.Synctext

generate sCChartsExp "http://kieler.cs.cau.de/yakindu/sccharts/stext/"

import "http://kieler.cs.cau.de/yakindu/stext/" as synctext
import "http://www.eclipse.org/emf/2002/Ecore" as ecore
import "http://www.yakindu.org/sct/statechart/SText" as stext
import "http://www.yakindu.org/sct/sgraph/2.0.0" as sgraph
import "http://www.yakindu.org/base/types/2.0.0" as types


/************************************************/
/*			 Variable Definition				*/
/************************************************/
// Override the SText VariableDefinition rule
// A variable is a Declaration. It has a Direction, a Name, a Type, an InitialValue and a CombineOperator
/* ---- variable definition ---- */
VariableDefinition:
	{VariableDefinition} (isInput?='input')? (isOutput?='output')? (isStatic?='static')? type=[types::Type|FQN] name=ID
	('=' initialValue=Expression)? ('with' varCombineOperator=CombineOperator)? ';';