<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="scgbb" nsURI="http://kieler.cs.cau.de/scgbb/0.1.0" nsPrefix="scgbb">
  <eClassifiers xsi:type="ecore:EClass" name="SCGraphBB" eSuperTypes="scgdep.ecore#//SCGraphDep">
    <eStructuralFeatures xsi:type="ecore:EReference" name="basicBlocks" upperBound="-1"
        eType="#//BasicBlock" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="schedulingBlocks" upperBound="-1"
        eType="#//SchedulingBlock" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guards" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ValuedObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predecessors" upperBound="-1"
        eType="#//BasicBlock"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockType" eType="#//BlockType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditional" eType="ecore:EClass scg.ecore#//Conditional"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="goBlock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SchedulingBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="ecore:EClass scg.ecore#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencies" upperBound="-1"
        eType="ecore:EClass scgdep.ecore#//Dependency"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" lowerBound="1" eType="ecore:EClass ../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ValuedObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BlockType">
    <eLiterals name="NORMAL"/>
    <eLiterals name="DEPTH" value="1"/>
    <eLiterals name="TRUEBRANCH" value="2"/>
    <eLiterals name="ELSEBRANCH" value="3"/>
    <eLiterals name="SYNCHRONIZER" value="4"/>
  </eClassifiers>
</ecore:EPackage>
