<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="scgsched" nsURI="http://kieler.cs.cau.de/scgsched/0.1.0" nsPrefix="scgsched">
  <eClassifiers xsi:type="ecore:EClass" name="SCGraphSched" eSuperTypes="scgbb.ecore#//SCGraphBB">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unschedulable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schedules" upperBound="-1"
        eType="#//Schedule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="problems" upperBound="-1"
        eType="#//Problem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guards" upperBound="-1"
        eType="#//GuardExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmptyExpressions">
    <eStructuralFeatures xsi:type="ecore:EReference" name="valuedObject" lowerBound="1"
        eType="ecore:EClass ../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ValuedObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="ecore:EClass ../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GuardExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="valuedObject" lowerBound="1"
        eType="ecore:EClass ../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ValuedObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="ecore:EClass ../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="emptyExpressions" upperBound="-1"
        eType="#//EmptyExpressions" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Schedule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="schedulingBlocks" upperBound="-1"
        eType="ecore:EClass scgbb.ecore#//SchedulingBlock"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Problem"/>
  <eClassifiers xsi:type="ecore:EClass" name="PotentialInstantaneousLoopProblem" eSuperTypes="#//Problem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="controlFlows" upperBound="-1"
        eType="ecore:EClass scg.ecore#//ControlFlow"/>
  </eClassifiers>
</ecore:EPackage>
