/**
 *
 * $Id$
 */
package de.cau.cs.kieler.circuit.validation;

import de.cau.cs.kieler.circuit.Actor;
import de.cau.cs.kieler.circuit.Link;
import de.cau.cs.kieler.circuit.Port;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.cau.cs.kieler.circuit.Actor}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActorValidator {
	boolean validate();

	boolean validateInnerActors(EList<Actor> value);
	boolean validateInnerLinks(EList<Link> value);
	boolean validatePorts(EList<Port> value);
	boolean validateType(String value);
}
