/**
 * generated by Xtext 2.12.0
 */
package de.cau.cs.kieler.ehelp.eHelp;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Table Row</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.cau.cs.kieler.ehelp.eHelp.TableRow#getCells <em>Cells</em>}</li>
 * </ul>
 *
 * @see de.cau.cs.kieler.ehelp.eHelp.EHelpPackage#getTableRow()
 * @model
 * @generated
 */
public interface TableRow extends EObject
{
  /**
   * Returns the value of the '<em><b>Cells</b></em>' containment reference list.
   * The list contents are of type {@link de.cau.cs.kieler.ehelp.eHelp.TableCell}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cells</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cells</em>' containment reference list.
   * @see de.cau.cs.kieler.ehelp.eHelp.EHelpPackage#getTableRow_Cells()
   * @model containment="true"
   * @generated
   */
  EList<TableCell> getCells();

} // TableRow
