/*
 * generated by Xtext
 */
package de.cau.cs.kieler.kivis.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor
import org.eclipse.xtext.ui.editor.IXtextEditorCallback
import org.eclipse.xtext.ui.editor.validation.ValidatingEditorCallback

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class KiVisUiModule extends AbstractKiVisUiModule {
    
    // The plug-in ID
    public static final String PLUGIN_ID = "de.cau.cs.kieler.kivis.ui"; //$NON-NLS-1$
    
    public static final String LAST_KIVIS_FILE = "last_used_kivis_file";
    
    def Class<? extends IXtextEditorCallback> bindIXtextEditorCallback() {
        return ValidatingEditorCallback
    }
}
