/*
 * generated by Xtext
 */
package de.cau.cs.kieler.kivis.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractKiVisScopeProvider extends DelegatingScopeProvider {
}
