<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="quartz"
    nsURI="http://www.cau.de/cs/kieler/quartz/editor/Quartz" nsPrefix="quartz">
  <eClassifiers xsi:type="ecore:EClass" name="QrzFile">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" eType="#//ImportList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="macros" upperBound="-1"
        eType="#//MacroDef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" eType="#//QModule"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackagePath" eSuperTypes="#//QrzFile"/>
  <eClassifiers xsi:type="ecore:EClass" name="ImportList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imp" upperBound="-1" eType="#//PointedName"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PointedName" eSuperTypes="#//PackagePath">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" upperBound="-1" eType="#//PointedName"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="all" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MacroDef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//QName"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" eType="#//QNameList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//UtyExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QModule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//Name" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intf" eType="#//InterfaceList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stmt" eType="#//LocStmt"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="obs" upperBound="-1" eType="#//ObservedSpecList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObservedSpecList"/>
  <eClassifiers xsi:type="ecore:EClass" name="Name" eSuperTypes="#//QName">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QName" eSuperTypes="#//InOutName #//UtyExpr #//Generic #//NamedStmt">
    <eStructuralFeatures xsi:type="ecore:EReference" name="t6" eType="#//UtyExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t5" eType="#//UtyExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t24" eType="#//AtomicStmt"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exprs" eType="#//OptUtyExprList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t10" eType="#//AtomicStmt"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QNameList" eSuperTypes="#//ControlList #//AssumeList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//QName"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="names" upperBound="-1"
        eType="#//QNameList" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ta" eType="#//UtyExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tb" eType="#//UtyExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tc" eType="#//UtyExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dims" eType="#//DimList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QTypeList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//QType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t" upperBound="-1" eType="#//QType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DimList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" upperBound="-1" eType="#//UtyExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InOutName" eSuperTypes="#//InOutNameList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="names" upperBound="-1"
        eType="#//InOutName" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InOutNameList"/>
  <eClassifiers xsi:type="ecore:EClass" name="InOutNameListComma">
    <eStructuralFeatures xsi:type="ecore:EReference" name="names" upperBound="-1"
        eType="#//InOutName" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//QType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="names" eType="#//InOutNameList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceComma">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//QType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="names" eType="#//InOutNameListComma"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="intf" eType="#//Interface"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaces" upperBound="-1"
        eType="#//Interface" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlList"/>
  <eClassifiers xsi:type="ecore:EClass" name="AssumeList"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProofGoalList" eSuperTypes="#//ObservedSpecList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" upperBound="-1" eType="#//QName"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" upperBound="-1" eType="#//UtyExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="goals" upperBound="-1"
        eType="#//ProofGoalList" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ver" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ctrl" upperBound="-1" eType="#//ControlList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ass" upperBound="-1" eType="#//AssumeList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ctr" upperBound="-1" eType="#//ControlList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FixpointEqList" eSuperTypes="#//UtyExpr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr2" eType="#//UtyExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OptUtyExpr" eSuperTypes="#//OptUtyExprList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tk" eType="#//UtyExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exprs" upperBound="-1"
        eType="#//OptUtyExprList" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OptUtyExprList"/>
  <eClassifiers xsi:type="ecore:EClass" name="UtyExprSelectList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tk" eType="#//UtyExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UtyExpr" eSuperTypes="#//UtyAction #//dUtyExpr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t7" eType="#//UtyExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//QName"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//QType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t2" eType="#//UtyExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t4" eType="#//UtyExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UtyAction" eSuperTypes="#//AtomicStmt"/>
  <eClassifiers xsi:type="ecore:EClass" name="case_list" eSuperTypes="#//AtomicStmt">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp" upperBound="-1" eType="#//dUtyExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stmt" upperBound="-1" eType="#//Stmt"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t15" eType="#//AtomicStmt"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="dUtyExpr" eSuperTypes="#//dUtyExprs #//AtomicStmt">
    <eStructuralFeatures xsi:type="ecore:EReference" name="t13" eType="#//AtomicStmt"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t14" eType="#//AtomicStmt"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t07" eType="#//AtomicStmt"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="dUtyExprs"/>
  <eClassifiers xsi:type="ecore:EClass" name="Generic" eSuperTypes="#//UtyExpr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="t23" eType="#//AtomicStmt"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t" eType="#//AtomicStmt"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocStmt" eSuperTypes="#//AtomicStmt">
    <eStructuralFeatures xsi:type="ecore:EReference" name="locals" upperBound="-1"
        eType="#//InterfaceList" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stmt" eType="#//Stmt" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SeqStmt">
    <eStructuralFeatures xsi:type="ecore:EReference" name="s" upperBound="-1" eType="#//AtomicStmt"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stmt">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//SeqStmt"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" upperBound="-1"
        eType="#//SeqStmt" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AtomicStmt">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//dUtyExprs"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t03" eType="#//AtomicStmt"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t16" eType="#//AtomicStmt"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t06" eType="#//dUtyExprs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedStmt" eSuperTypes="#//AtomicStmt"/>
</ecore:EPackage>
