<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sCChartsExp" nsURI="http://www.cau.de/cs/kieler/yakindu/sccharts/model/scchartstext/scchartstext/SCChartsExp"
    nsPrefix="sCChartsExp">
  <eClassifiers xsi:type="ecore:EClass" name="StateScope" eSuperTypes="../../../../../../../../../../../org.yakindu.sct.model.sgraph/model/emf/sgraph.ecore#//Scope"/>
  <eClassifiers xsi:type="ecore:EClass" name="SignalDefinition" eSuperTypes="../../../../../../../../../../../org.yakindu.sct.model.sgraph/model/emf/sgraph.ecore#//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDefinition" eSuperTypes="../../../../../../../../../../../org.yakindu.sct.model.stext/model/SText.ecore#//VariableDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//VarDirection"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStatic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="varInitialValue" eType="ecore:EClass ../../../../../../../../../../../org.yakindu.sct.model.stext/model/SText.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="varCombineOperator" eType="#//CombineOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalReaction" eSuperTypes="../../../../../../../../../../../org.yakindu.sct.model.stext/model/SText.ecore#//LocalReaction"/>
  <eClassifiers xsi:type="ecore:EClass" name="StateReaction" eSuperTypes="../../../../../../../../../../../org.yakindu.sct.model.stext/model/SText.ecore#//EventSpec"/>
  <eClassifiers xsi:type="ecore:EClass" name="Entry" eSuperTypes="#//StateReaction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Inside" eSuperTypes="#//StateReaction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Exit" eSuperTypes="#//StateReaction"/>
  <eClassifiers xsi:type="ecore:EEnum" name="CombineOperator">
    <eLiterals name="NONE" literal="'none'"/>
    <eLiterals name="ADD" value="1" literal="'+'"/>
    <eLiterals name="MULT" value="2" literal="'*'"/>
    <eLiterals name="MAX" value="3" literal="'max'"/>
    <eLiterals name="MIN" value="4" literal="'min'"/>
    <eLiterals name="OR" value="5" literal="'or'"/>
    <eLiterals name="AND" value="6" literal="'and'"/>
    <eLiterals name="HOST" value="7" literal="'host'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VarDirection">
    <eLiterals name="INOUT" literal="inputoutut"/>
    <eLiterals name="IN" value="1" literal="input"/>
    <eLiterals name="OUT" value="2" literal="output"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleScope" eSuperTypes="#//StateScope"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventDefinition" eSuperTypes="#//SignalDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReactionTrigger" eSuperTypes="../../../../../../../../../../../org.yakindu.sct.model.sgraph/model/emf/sgraph.ecore#//Trigger">
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggers" upperBound="-1"
        eType="ecore:EClass ../../../../../../../../../../../org.yakindu.sct.model.stext/model/SText.ecore#//EventSpec"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guardExpression" eType="ecore:EClass ../../../../../../../../../../../org.yakindu.sct.model.stext/model/SText.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isImmediate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delay" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReactionEffect" eSuperTypes="../../../../../../../../../../../org.yakindu.sct.model.sgraph/model/emf/sgraph.ecore#//Effect">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="ecore:EClass ../../../../../../../../../../../org.yakindu.sct.model.stext/model/SText.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreValueExpressionreturns" eSuperTypes="../../../../../../../../../../../org.yakindu.sct.model.stext/model/SText.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass ../../../../../../../../../../../org.yakindu.sct.model.stext/model/SText.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
