grammar de.cau.cs.kieler.scol.SCOL with de.cau.cs.kieler.scl.SCL
  
import "http://www.eclipse.org/emf/2002/Ecore" as ecore
import "http://kieler.cs.cau.de/annotations" as annotations
import "http://kieler.cs.cau.de/kexpressions/0.1.2" as kexpressions
import "http://kieler.cs.cau.de/keffects/0.1.0" as keffects
import "http://kieler.cs.cau.de/kext/0.1.0" as kext
import "http://kieler.cs.cau.de/scl/0.2.0" as scl
generate scol "http://www.cau.de/cs/kieler/scol/0.1.0"

SCOLProgram:
    pragmas+=Pragma*
    modules+=Module*
;