
load model-checker.maude
load STATES
load EVENTS
load ACTIONS
load TRANS
load SM
load STEPSEM

fmod eclipseInterface is
 including STATEMACHINE .
 including TRANSITIONS .
 including STATES .
*** // Events //
  ops ee1 ee0 ee0 res ee1 susp : -> Event .
  op allEvents : -> Events .

*** // allActions //	
  ops a3 a4 a4  a1  : -> Action .

***// States //
  ops CB CG Cinner CE Csusp CN Couter : -> ModState .	
    eq CB = root(R "root") : C "outer" : R "inOuter" : C "B" .
    eq CG = root(R "root") : C "outer" : R "inOuter" : C "inner" : R "inInner0" : C "G" .
    eq Cinner = root(R "root") : C "outer" : R "inOuter" : C "inner" .
    eq CE = root(R "root") : C "outer" : R "inOuter" : C "inner" : R "inInner0" : C "E" .
    eq Csusp = root(R "root") : C "susp" .
    eq CN = root(R "root") : C "outer" : R "inOuter" : C "inner" : R "inInner1" : C "N" .
    eq Couter = root(R "root") : C "outer" .	
***// Regions //
  ops RinInner1 RinOuter RinInner0 Rroot : -> Region .
    eq RinInner1 = root(R "root") : C "outer" : R "inOuter" : C "inner" : R "inInner1" .
    eq RinOuter = root(R "root") : C "outer" : R "inOuter" .
    eq RinInner0 = root(R "root") : C "outer" : R "inOuter" : C "inner" : R "inInner0" .
    eq Rroot = root(R "root") .
***// allVerts //
  op allVerts : -> Verts .
  eq allVerts = RinInner1, RinOuter, RinInner0, Rroot , CB, CG, Cinner, CE, Csusp, CN, Couter .
	
***// defaults //
  ops defRinInner1 defRinOuter defRinInner0 defRroot : -> Default .
 eq defRroot = Rroot default Couter .
 eq defRinOuter = RinOuter default CB .
 eq defRinInner0 = RinInner0 default CE .
 eq defRinInner1 = RinInner1 default CN .
  op allDefs : -> Defaults .
  eq allDefs = defRinInner1, defRinOuter, defRinInner0, defRroot .
  
***// deep defaults //
  ops dDefRinInner1 dDefRinOuter dDefRinInner0 dDefRroot : -> DeepDefault .
 eq dDefRinOuter = RinOuter deepdefault CB .
  op allDHDefs : -> DeepDefaults .
  eq allDHDefs = dDefRinInner1, dDefRinOuter, dDefRinInner0, dDefRroot .

***// shallow defaults //
  ops sDefRinInner1 sDefRinOuter sDefRinInner0 sDefRroot : -> ShallowDefault .
  
  op allSHDefs : -> ShallowDefaults .
  eq allSHDefs = sDefRinInner1, sDefRinOuter, sDefRinInner0, sDefRroot .

*** Transitions 
*** ToDo: (Important): Compute sources and targets sets
*** ToDo: Remove initial states transitions (DONE?) 
  ops F2N_S-ydsIuKEd-yoIYGk1D8vA  G2_Zk1koIuKEd-yoIYGk1D8vA  I2outer_H6AhoIuKEd-yoIYGk1D8vA  F2E_ob7KIIuJEd-yoIYGk1D8vA  I2B_ub69sIuJEd-yoIYGk1D8vA  J2_XzxPoIuKEd-yoIYGk1D8vA  B2F_qDngsIuJEd-yoIYGk1D8vA  susp2DH_LbxYMIuKEd-yoIYGk1D8vA  N2J_WOFEMIuKEd-yoIYGk1D8vA  G2J_VgYQsIuKEd-yoIYGk1D8vA  E2G_lT5CMIuJEd-yoIYGk1D8vA  DH2B_NM-3IIuKEd-yoIYGk1D8vA  I2E_jRuWIIuJEd-yoIYGk1D8vA  I2N_SZjCoIuKEd-yoIYGk1D8vA  outer2susp_I39-sIuKEd-yoIYGk1D8vA :-> ModTransition .
eq tr_F2N_S-ydsIuKEd-yoIYGk1D8vA = F_XkAKwIuJEd-yoIYGk1D8vA null nil skip empty empty empty RinOuter .
eq tr_G2_Zk1koIuKEd-yoIYGk1D8vA = G_gmI5oIuJEd-yoIYGk1D8vA ee1 nil a3 empty empty empty RinInner0 .
eq tr_F2E_ob7KIIuJEd-yoIYGk1D8vA = F_XkAKwIuJEd-yoIYGk1D8vA null nil skip empty empty empty RinOuter .
eq tr_J2_XzxPoIuKEd-yoIYGk1D8vA = J_Uhp-oIuKEd-yoIYGk1D8vA ee0 nil a4 empty empty empty RinOuter .
eq tr_B2F_qDngsIuJEd-yoIYGk1D8vA = B_aCTZMIuJEd-yoIYGk1D8vA ee0 nil a4 empty empty empty RinOuter .
eq tr_susp2DH_LbxYMIuKEd-yoIYGk1D8vA = susp_FiQnIIuKEd-yoIYGk1D8vA res nil  empty empty empty Rroot .
eq tr_N2J_WOFEMIuKEd-yoIYGk1D8vA = N_RL-cQIuKEd-yoIYGk1D8vA null nil skip empty empty empty RinInner1 .
eq tr_G2J_VgYQsIuKEd-yoIYGk1D8vA = G_gmI5oIuJEd-yoIYGk1D8vA null nil skip empty empty empty RinInner0 .
eq tr_E2G_lT5CMIuJEd-yoIYGk1D8vA = E_fj2WMIuJEd-yoIYGk1D8vA ee1 nil a1 empty empty empty RinInner0 .
eq tr_DH2B_NM-3IIuKEd-yoIYGk1D8vA = DH_KS5roIuKEd-yoIYGk1D8vA null nil skip empty empty empty RinOuter .
eq tr_outer2susp_I39-sIuKEd-yoIYGk1D8vA = outer_PpBRMIuJEd-yoIYGk1D8vA susp nil  empty empty empty Rroot .  
  op allTrans :-> Transitons .
  eq allTrans = F2N_S-ydsIuKEd-yoIYGk1D8vA  G2_Zk1koIuKEd-yoIYGk1D8vA  I2outer_H6AhoIuKEd-yoIYGk1D8vA  F2E_ob7KIIuJEd-yoIYGk1D8vA  I2B_ub69sIuJEd-yoIYGk1D8vA  J2_XzxPoIuKEd-yoIYGk1D8vA  B2F_qDngsIuJEd-yoIYGk1D8vA  susp2DH_LbxYMIuKEd-yoIYGk1D8vA  N2J_WOFEMIuKEd-yoIYGk1D8vA  G2J_VgYQsIuKEd-yoIYGk1D8vA  E2G_lT5CMIuJEd-yoIYGk1D8vA  DH2B_NM-3IIuKEd-yoIYGk1D8vA  I2E_jRuWIIuJEd-yoIYGk1D8vA  I2N_SZjCoIuKEd-yoIYGk1D8vA  outer2susp_I39-sIuKEd-yoIYGk1D8vA .


***/// A state machine consits of Vertices Defaultsstatesfunction ShallowDefaultstatesfunction DeepDefaultstatesfunction EntryActionsfunction ExitActionsFunction Transitions 
  op SMINT : -> StateMachine .
  ***// ToDo: add entry/exit actions//
  eq SMINT = (SM allVerts allDefs allSHDefs allDHDefs empty empty allTrans) .

  
endfm
***(
mod TSS is
	including SATISFACTION .
	including STEPSEM .
	including eclipseInterface .
	including LTL .
	including MODEL-CHECKER .
	including LTL-SIMPLIFIER .
***(
	op init : -> MState .
	eq init = (maState "UML" ($stableC (prettyVerts cf1) empty) (ee0, ee1, ee2, ee3, ee4)) .
)***	
	var msst mastate : MState .
	vars V V2 : Verts .
	var ac ac2 : Actions .
	var T : Transitions .
	var ES : EventSS .
	var mode : String .
	vars HC : HistoryConfs .
	
	subsort MState < State .
	
	op aCf : Actions -> Prop .
	op inC : Verts -> Prop .
	eq maState mode ($stableC V HC) ES |= inC(V2) = (prettyVerts V2) subset V  .
	eq maState mode ($unstableC V HC T ac) ES |= aCf(ac2) = actionConflict par (ac ac2) .
	eq maState mode ($unstableC V HC T ac) ES |= aCf(nil) = actionConflict ac .
endm
)***
	