/**
 * generated by Xtext
 */
package de.cau.cs.kieler.lustre.lustre;

import de.cau.cs.kieler.kexpressions.Expression;
import de.cau.cs.kieler.kexpressions.VariableDeclaration;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.cau.cs.kieler.lustre.lustre.LustreVariableDeclaration#getClockExpr <em>Clock Expr</em>}</li>
 * </ul>
 *
 * @see de.cau.cs.kieler.lustre.lustre.LustrePackage#getLustreVariableDeclaration()
 * @model
 * @generated
 */
public interface LustreVariableDeclaration extends VariableDeclaration
{
  /**
   * Returns the value of the '<em><b>Clock Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Clock Expr</em>' containment reference.
   * @see #setClockExpr(Expression)
   * @see de.cau.cs.kieler.lustre.lustre.LustrePackage#getLustreVariableDeclaration_ClockExpr()
   * @model containment="true"
   * @generated
   */
  Expression getClockExpr();

  /**
   * Sets the value of the '{@link de.cau.cs.kieler.lustre.lustre.LustreVariableDeclaration#getClockExpr <em>Clock Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Clock Expr</em>' containment reference.
   * @see #getClockExpr()
   * @generated
   */
  void setClockExpr(Expression value);

} // LustreVariableDeclaration
