/**
 * generated by Xtext 2.10.0
 */
package de.cau.cs.kieler.lustre.lustre;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sel Tranche End</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.cau.cs.kieler.lustre.lustre.LustrePackage#getSelTrancheEnd()
 * @model
 * @generated
 */
public interface SelTrancheEnd extends EObject
{
} // SelTrancheEnd
