<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="transitionlabel"
    nsURI="http://kieler.cs.cau.de/synccharts/actionlabel" nsPrefix="transitionlabel">
  <eClassifiers xsi:type="ecore:EClass" name="IntValue" eSuperTypes="#//Value http://kieler.cs.cau.de/synccharts#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FloatValue" eSuperTypes="#//Value http://kieler.cs.cau.de/synccharts#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanValue" eSuperTypes="#//Value http://kieler.cs.cau.de/synccharts#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value"/>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="http://kieler.cs.cau.de/synccharts#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subExpressions" upperBound="-1"
        eType="ecore:EClass http://kieler.cs.cau.de/synccharts#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="ecore:EEnum http://kieler.cs.cau.de/synccharts#//OperatorType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subExpression" upperBound="-1"
        eType="ecore:EClass http://kieler.cs.cau.de/synccharts#//Expression" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
