/*
* generated by Xtext
*/
package de.cau.cs.kieler.yakindu.sccharts.model.scchartstext.scchartstext.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class SCChartsExpOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
