<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="keffects" nsURI="http://kieler.cs.cau.de/keffects/0.1.0" nsPrefix="keffects">
  <eClassifiers xsi:type="ecore:EClass" name="Effect" abstract="true" interface="true"
      eSuperTypes="../../de.cau.cs.kieler.annotations/model/annotations.ecore#//Annotatable kexpressions.ecore#//Schedulable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Assignment" eSuperTypes="#//Effect">
    <eStructuralFeatures xsi:type="ecore:EReference" name="valuedObject" eType="ecore:EClass kexpressions.ecore#//ValuedObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass kexpressions.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indices" upperBound="-1"
        eType="ecore:EClass kexpressions.ecore#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//AssignOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subReference" eType="ecore:EClass kexpressions.ecore#//ValuedObjectReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AssignOperator">
    <eLiterals name="ASSIGN"/>
    <eLiterals name="ASSIGNADD" value="1"/>
    <eLiterals name="ASSIGNSUB" value="2"/>
    <eLiterals name="ASSIGNMUL" value="3"/>
    <eLiterals name="ASSIGNDIV" value="4"/>
    <eLiterals name="ASSIGNMOD" value="5" literal="ASSIGNMOD"/>
    <eLiterals name="ASSIGNAND" value="6"/>
    <eLiterals name="ASSIGNOR" value="7" literal="ASSIGNOR"/>
    <eLiterals name="ASSIGNXOR" value="8"/>
    <eLiterals name="POSTFIXADD" value="9"/>
    <eLiterals name="POSTFIXSUB" value="10"/>
    <eLiterals name="ASSIGNMIN" value="11"/>
    <eLiterals name="ASSIGNMAX" value="12" literal=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Emission" eSuperTypes="#//Effect">
    <eStructuralFeatures xsi:type="ecore:EReference" name="valuedObject" lowerBound="1"
        eType="ecore:EClass kexpressions.ecore#//ValuedObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newValue" eType="ecore:EClass kexpressions.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HostcodeEffect" eSuperTypes="#//Effect kexpressions.ecore#//TextExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceCallEffect" eSuperTypes="#//Effect kexpressions.ecore#//ReferenceCall"/>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionCallEffect" eSuperTypes="#//Effect kexpressions.ecore#//FunctionCall"/>
  <eClassifiers xsi:type="ecore:EClass" name="PrintCallEffect" eSuperTypes="#//Effect kexpressions.ecore#//PrintCall"/>
</ecore:EPackage>
